### ISSUE TITLE
No /dev/ttyUSB0 in HassOS for deCONZ FTDI usb dongle

### ISSUE THREAD

**Issue by snozzlebert** [home-assistant/hassos#104]
I tried to setup HassOS in Proxmox (KVM). Almost everything works as expected, HassOS boots and Home Assistant is running.
However, `/dev/ttyUSB0` is not found in HassOS.
I think the drivers for the deCONZ USB dongle are not loaded. The device is found in the VM:
```
dmesg | grep FTDI
[    3.214149] usb 3-1: Manufacturer: FTDI
```
```
lsusb
...
Bus 003 Device 002: ID 0403:6015
```

In my original HassIO generic install on Ubuntu Server the folowing drivers where loaded for this device:
```
usbserial
ftdi_sio
```

```
dmesg | grep FTDI
[    2.418960] usb 1-6: Manufacturer: FTDI
[    3.904772] usbserial: USB Serial support registered for FTDI USB Serial Device
[    3.904858] ftdi_sio 1-6:1.0: FTDI USB Serial Device converter detected
[    3.908125] usb 1-6: FTDI USB Serial Device converter now attached to ttyUSB0
```

```
lsusb
...
Bus 001 Device 004: ID 0403:6015 Future Technology Devices International, Ltd Bridge(I2C/SPI/UART/FIFO)
```

How do I get this working in HassOS?

**Comment by pvizeli** [comment]
Make a PR with needed kernel configs: https://github.com/home-assistant/hassos/blob/dev/buildroot-external/board/ova/kernel.config
