### ISSUE TITLE
I can't install into rpi 3B by this version 1.5 .

### ISSUE THREAD

**Issue by gotodragon** [home-assistant/hassos#106]
HI:
I use version 1.3 into RPI 3B is ok, but use new version 1.5 32Bit or 64Bit are all no answer by checking data,RPI 3B  are always red light on right side.
So, I don't know what is different between 1.3 and 1.5 on Installation method，anyway，this version 1.5  can not install into RPI 3B. 
I change many different SD 16G ,32G and  RPI 3B are same.
so please check what's problem for this version.

Dragon

**Comment by pvizeli** [comment]
Try the 1.7 - build is in progress.

**Comment by tyborall** [comment]
1.5 on RPi 3B+ runs without problems.

**Comment by BenNeumeister** [comment]
This is RPi 3B (non plus).
Part# a02082

Seeing as the network controllers are different, might be something to do wit that.
Where would we find the beta builds. Can't seem to find any links from Git, just the release ones.

**Comment by tyborall** [comment]
It is fixed with 1.7 which is already in the build process. So just wait until it is finished...

**Comment by pvizeli** [comment]
Is now okay with 1.7 ?
