### ISSUE TITLE
MAC ERROR: the disk you inserted was not readable

### ISSUE THREAD

**Issue by robmarkcole** [home-assistant/hassos#110]
On flashing the latest image of HassioOS on Mac with etcher, on completion I see the following and cannot access the disk - any advice? When I insert the SD card into the pi HassOS does boot up, but since I cannot edit the network file via my Mac I cannot setup wifi.

![image](https://user-images.githubusercontent.com/11855322/42746023-babd2d1a-88cd-11e8-848c-91bbcecae68b.png)

**Comment by pvizeli** [comment]
You need a usb stick and not edit the SDcard :) Maybe the Mac OSX don't support GPT legacy mode.

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassos/blob/dev/Documentation/configuration.md

**Comment by robmarkcole** [comment]
OK the [docs](https://www.home-assistant.io/hassio/installation/) need updating then as states:
```
Optional - Setup the WiFi or static IP: On the SD-card, create the network/my-network file and follow the HassOS howto.
```

**Comment by pvizeli** [comment]
Where you see that? I can't find this...

**Comment by robmarkcole** [comment]
https://www.home-assistant.io/hassio/installation/

**Comment by cogneato** [comment]
It should just say

> Optional - To setup WiFi or a static IP, follow the HassOS howto.

The reference to SD is incorrect.

**Comment by frenck** [comment]
PR has been merged. This issue may be closed now.

**Comment by smuda** [comment]
There are other references to the SD-card as well. The one I stumbled upon is
[https://www.home-assistant.io/hassio/zwave/](https://www.home-assistant.io/hassio/zwave/)

Sorry if this is obvious, but why isn't it possible to open the SD-card in a mac?

**Comment by rudders** [comment]
The file system used by HASSOS on the SD card is not compatible with MacOS. A Linux VM on your Mac would be able to read it as a work around.

**Comment by virgilm** [comment]
This is still a problem/confusing. Had to google it to get to this page.

The installation [page](https://www.home-assistant.io/hassio/installation/) still says:
"Optional - set up the Wi-Fi or a static IP address. There are two possible places for that:"

Linux VM is indeed a valid workaround.

**Comment by tmm1** [comment]
See https://gist.github.com/miguelmota/d1d70d19fbd763afdd65c5c1375ddbde#gistcomment-2735565

h/t https://community.home-assistant.io/t/how-to-access-config-txt-in-hassio/139330/19
