### ISSUE TITLE
Update to HassOS 17 never ends

### ISSUE THREAD

**Issue by andlo** [home-assistant/hassos#111]
I did try pressing UPDATE on Hass.io System page, but after really long time it never came up again.

I then did a ard restart and it came up still running 15.

Is updating working, ad how long time is one to expect it takes ?

**Comment by pvizeli** [comment]
Doublicate of Hass.io issue: https://github.com/home-assistant/hassio/issues/565

Please update this bug report with additional information like hardware. We can try a manual update and look the output.
