### ISSUE TITLE
RaspberryPi: Green LED flashes twice

### ISSUE THREAD

**Issue by gotodragon** [home-assistant/hassos#116]
HI
Today I try and test again hassos ver. 1.7 for 32bit and 64bit , it is very sad, the same situation is with ver 1.5, no data transfer by checking. waiting for almost 20 minutes every time.
I test it  by  different  RPI 3B and different SD, it is also same. please check the reason.

regards

Dragon

**Comment by tomh05** [comment]
I'm also having issues getting 1.7 to work on my Raspberry pi 3.

**Steps:**
- Download https://github.com/home-assistant/hassos/releases/download/1.7/hassos_rpi3-64-1.7.img.gz
- Flash using Etcher 1.4.4
- I get the message "the disk you inserted was not readable by this computer"
- When I put SD card in Raspberry Pi 3 Model B and power on, Green LED flashes twice, then no further activity

**Comment by pleeja** [comment]
I get the same "the disk you inserted was not readable by this computer".

**Comment by cogneato** [comment]
@tomh05 @pleeja have either of you tried extracting the img from the archive first before flashing?

**Comment by mihalski** [comment]
The "the disk you inserted was not readable by this computer" message is expected and not a problem.

**Comment by pvizeli** [comment]
What do you see on screen?

The message: "the disk you inserted was not readable by this computer" is not a problem. Only if you system will support ext4 and GPT legacy. And that is not given with Windows / OSx

**Comment by tomh05** [comment]
I didn't have a screen plugged in to the pi, but given the green SD card
activity LED flashed twice and then nothing, this usually indicates that no
bootable OS was found on the SD card. Usually you will get many green
flashes as the OS loads off the SD card during boot.

Therefore I would not expect the Pi to have anything on its display. I can
check this evening though.

**Comment by pvizeli** [comment]
Flash the SD card with etcher and eject the card simple manual out after the etcher is done. Don't klick on any message and don't allow your OS to format the SD card again. Then should it work.

**Comment by tomh05** [comment]
@pvizeli Those are the exact steps I took, still no luck.

**Comment by pvizeli** [comment]
The problem look like, that you Computer automatic reformat the SDcard and breake it or you images is still defect. Do you have try to download it new from website?

Can you try the dd variant:
https://www.raspberrypi.org/documentation/installation/installing-images/mac.md

**Comment by pvizeli** [comment]
OR this: https://www.thefanclub.co.za/how-to/dd-utility-write-and-backup-operating-system-img-files-memory-card-mac-os-x

**Comment by gotodragon** [comment]
@pvizeli I try gz  files，in fact，the file automatically extract by MAC OS, now I test gz.

**Comment by gotodragon** [comment]
I try it again, flash Gz file for 1.7 32bit and just take out SD card from MAC , no click and others after flash Sd card, it is same, nothing happen for insert SD with ver. 1.7 into RPI 3B. so please check it, much pepole ask  questions about this version on the BBS in china. so it is  really problem about the file.

**Comment by tomh05** [comment]
I've just tried again with 1.7 32 bit and it's working for me - apologies!
@gotodragon I'd recommend plugging in an HDMI screen and seeing if you get anything.

**Comment by pvizeli** [comment]
Look like that is a OSX only problem? I think if you use the same image on a linux or windows to flash the SD, it works. That create the question, what does OSX automatic and how we can stop this automatic to not destroy the partition layout on SD card?

**Comment by tomh05** [comment]
I'm not sure OSX is actually doing anything to the partition - it gives you a prompt box saying "the disk you inserted was not readable by this computer" and just asks you to initialise/ignore/eject it

![dialog](https://www.easeus.com/mac/images/feature-screen/the-disk-you-inserted-was-not-readable-by-this-computer.png)

I suspect as long as you eject, it won't write anything to the volume.

**Comment by pvizeli** [comment]
@tomh05 that is also my feeling. But @gotodragon have a other expirence.

I try to reflect the problem:
- 1) Images are okay / They have a boot partition
- 2) Etcher flash the image. I have no problem with that but we have no warrenty
- 3) OSX, should not change partition/fs if we simple `Eject` it or `Ignore`
- 4) Rpi don't boot with 2 green flash that mean, no boot partition

So we can be sure that 1 and 2 are not a problem. In that case we have 2, 3. Do a other flasher fix the problem @gotodragon ?

**Comment by tomh05** [comment]
Have you tried plugging an hdmi in? What do you see on the display? I got 2
flashes, then nothing for a while so I thought it was a boot problem, but
then after several seconds, I got more green flashes.

**Comment by pvizeli** [comment]
The boot process is like:

- First bootloader (broadcom): Search fat partition on first place
- First bootloader (broadcom): load rpi firmware (binary on boot partition)
- First Bootloader (RPI): Initial hardware and device tree
- First Bootloader (RPI): Load u-boot
- Second Bootloader (u-boot): init itself
- Second Bootloader (u-boot): load env from SD card (Information about active system)
- Second Bootloader (u-boot) start boot script from boot partition
- Second Bootloader (u-boot): load Kernel from SD into memory
- Second Bootloader (u-boot): boot linux kernel with device tree + options

2 Flash / reboot / 2 Flash -> is normaly from broadcom that he can't find a boot partition

**Comment by hteggi** [comment]
I could not get my Pi3 to boot with 1.5 or 1.7 when MH-Z19 CO2 Sensor was connected to GPIO serial pin 08 and 10 and green light would only flash two times when powered up. Removed MH-Z19 CO2 sensor from pin 8 and 10 and it boots fine. The MH-Z19 works fine on Pi2 with resinos. DHT 22 is working ok on pin 7 with 1.7 on Pi3.
Seems to be some difference in the way serial to GPIO is used from Pi2 to Pi3 due to bluetooth.
https://raspberrypi.stackexchange.com/questions/45570/how-do-i-make-serial-work-on-the-raspberry-pi3
In hardware for Hassos 1.7 I can only find:
 serial: /dev/ttyAMA0
input:
disk:
gpio:
gpiochip0
gpiochip128
gpiochip100
And no /dev/ttyS0 that is supposed to be the miniUART for GPIO on Pi3.
Not sure if this has anything to with the problem others are having.

Regards

hteggi
