### ISSUE TITLE
date/time is not correctly set on the Raspberry Pi 3B during first time power on

### ISSUE THREAD

**Issue by shiyush-git** [home-assistant/hassos#121]
The Raspberry 3B does not have a clock, when first time boot the system after flashed the image to SD card,  looks like the system doesn't sync the date/time with NTP, the wrong date, caused the hassos_supervisor can't connect to the server to download the landing page(SSL error: CERTIFICATE_VERIFY_FAILED).

**Comment by pvizeli** [comment]
They will be sync after the network is available with systemd timesync service. But they should ajust itself and work correctly after that?

**Comment by shiyush-git** [comment]
I have waited for couple hours in powner on state with LAN cable plugged, the date/time can't be synced, which NTP server used by default?

**Comment by pvizeli** [comment]
https://wiki.archlinux.org/index.php/systemd-timesyncd

**Comment by DavidFW1960** [comment]
I logged an issue in Home Assistant with time - my histories have all flatlined... I think the timezone is being ignored??? This may be a HassOS issue not HA? I only just switched from ResinOS.

**Comment by pvizeli** [comment]
Home Assistant is the time master. Maybe you need restart home assistant after you set the correct time zone inside config.

**Comment by DavidFW1960** [comment]
I was running the new 32bit HassOS on a Pi3B and took a snapshot; went to 64bit and restored. I think the database was the issue as after I deleted the database it's all working properly now.

**Comment by shiyush-git** [comment]
I just checked the timesyncd.conf, the default NTP server is time1.google.com, this probably is the reason why my Pi3 time can't not be synced, I am in China, thx gfw, no google at all.
But the tricky thing is the fallbackNTP setting looks like don't work.

**Comment by chc189** [comment]
最后怎么解决？@shiyush-git
