### ISSUE TITLE
USB stick missing from Hardware Info Page in VM

### ISSUE THREAD

**Issue by NK553** [home-assistant/hassos#122]
Running HassOS in a Vitualbox VM with USB passthrough on (as a USB 2.0 EHCI Controller) the device does not appear in the hardware page.  From the CLI, hassio hw info does not show it either.

Running 1.8

**Comment by pvizeli** [comment]
Can you debug that on host OS, if they available there?

**Comment by NK553** [comment]
During Initial VM loading, from the virtualbox log:

```
00:00:04.116633 EHCI: USB Operational
00:00:04.149572 EHCI: USB Suspended
00:00:04.149630 EHCI: Hardware reset
00:00:04.149675 EHCI: USB Operational
```

It is present and running in the logs, and shows up in a different ubuntu VM.

**Comment by NK553** [comment]
@cogneato couldn't get it to work either...

![image](https://user-images.githubusercontent.com/5782664/42946892-ad884aa6-8b31-11e8-91ea-403803b45881.png)

**Comment by NK553** [comment]
It's a USB Z-Wave stick, Aeotec Z-Stick Gen5, Z-Wave Plus USB.  It shows up in Windows device manager (HostOS) as "Sigma Designs, Inc as a com port...

It's a very common device in the community.  it worked perfectly in HassIO.

**Comment by NK553** [comment]
Where can I run lsusb?  Do I need to setup keys and ssh into 22222?  I couldn't get there from the hassio cli.

**Comment by NK553** [comment]
I GOT IT TO WORK!

I found the COM port in windows (COM7), forwarded that to my VM in Virtualbox as COM1, then put 

`zwave:
  usb_path: /dev/ttyS0
  polling_interval: 30000`

In my config.  Worked great.

**Comment by pvizeli** [comment]
You can login on terminal of virtualbox as root. Maybe I find out what kind of serial adapter it is :)
