### ISSUE TITLE
Raspberry Pi Camera Support

### ISSUE THREAD

**Issue by pschmitt** [home-assistant/hassos#123]
Hi,
I recently switched to HassOS. Almost everything works fine - except the Raspicam.

I appended the following lines to `config.txt`:
```
# Camera       
gpu_mem=128    
start_file=start_x.elf         
fixup_file=fixup_x.dat         
disable_camera_led=1
```

But this results in the Raspberry Pi not booting at all (no screen output, nothing). I tried this on both `armhf` and `aarch64`.
Is there any HassOS specific `config.txt` voodoo that I am missing? Thanks.

**Comment by pvizeli** [comment]
The extended firmware are not on SD card. If you want have it, you need self download it from raspberry repository and add it to boot partition. I will add a note documentation 👍
