### ISSUE TITLE
Add onewire

### ISSUE THREAD

**Issue by ezar** [home-assistant/hassos#129]
I want to add onewire but I can access to boot folder.

**Comment by pvizeli** [comment]
?

**Comment by ezar** [comment]
> 2018-07-24 19:07:10 ERROR (SyncWorker_2) [homeassistant.components.sensor.onewire] No onewire sensor found. Check if dtoverlay=w1-gpio is in your /boot/config.txt. Check the mount_dir parameter if it's defined

**Comment by cogneato** [comment]
config.txt is accessed through the SD on the hassos-boot partition, but I don't know if that is what you need here?

**Comment by JakobTewes** [comment]
How to access config.txt:
  - Copy “authorized_keys” via (FAT32 formatted, named “CONFIG”) USB stick.
    USB config can be imported via web interface -> hass.io -> system -> “Import from USB”
  - SSH to Host os via Port 22222 with user “root”
  - Edit config via
      vi /mnt/boot/config.txt

**Comment by danillab** [comment]
```sh
ssh root@hassio.local
ls /mnt/boot/
ls: /mnt/boot/: No such file or directory
```
How to mount boot?
how to edit the file /mnt/boot/config.txt ?

**Comment by pvizeli** [comment]
You need enable debug access or but the SD card on your computer.
