### ISSUE TITLE
[homeassistant.components.camera.rpi_camera] 'raspistill' was not found

### ISSUE THREAD

**Issue by sergiofraiman** [home-assistant/hassos#130]
It's raising this error when I am trying to use the [rpi_camera component](https://www.home-assistant.io/components/camera.rpi_camera/). 

`[homeassistant.components.camera.rpi_camera] 'raspistill' was not found`

Raspberry Pi 3 B+
HassOS 1.7
hassio version 1.3.1
home assistant version 0.74.0

**Comment by pvizeli** [comment]
With extended Firmware from raspberry repository?

**Comment by sergiofraiman** [comment]
no @pvizeli , just the plain installation from https://github.com/home-assistant/hassos/releases/download/1.7/hassos_rpi3-64-1.7.img.gz

**Comment by floowsn** [comment]
Same error with 

Raspberry Pi 3 B+
HassOS 1.9
hass 0.76.2

**Comment by Evanlec** [comment]
Same problem here
Raspberry Pi 3 B+
HassOS v1.13
HomeAssistant 0.84.3

There must be some way to install raspistill on HassOS?

**Comment by Scott8586** [comment]
Reactivating.  How can we get this fixed?
HassOS/Hassio
HA 0.92.0

**Comment by GrowFOUR** [comment]
Seriously! I have a Raspberry Pi 3 B+ with on board camera ribbon cable attached to genuine RPI camera V2 and I can't activate the camera rapistill because you cannot access so
 # Example configuration.yaml entry
camera:
  - platform: rpi_camera

DOES NOT WORK

**Comment by schmidt91** [comment]
I have the same issue. Raspberry Pi 3 + 0.93.1.

**Comment by Stebar59** [comment]
Do we really don't have a solution to have rpi_camera working?

**Comment by kotwox** [comment]
does not work. is there any hope?)

**Comment by marcinbauer85** [comment]
Can we get any response from the devs? Please 😢

**Comment by Stebar59** [comment]
Please, please .... please.

-------- Messaggio originale --------Da: marcinbauer85 <notifications@github.com> Data: 26/10/20  12:29  (GMT+01:00) A: home-assistant/operating-system <operating-system@noreply.github.com> Cc: Stebar59 <stefano.barbay@gmail.com>, Comment <comment@noreply.github.com> Oggetto: Re: [home-assistant/operating-system] [homeassistant.components.camera.rpi_camera] 'raspistill' was not found (#130) 

Can we get any response from the devs? Please 😢

**Comment by luci-11** [comment]
Logger: homeassistant.components.rpi_camera.camera
Source: components/rpi_camera/camera.py:42
Integration: Raspberry Pi Camera (documentation, issues)
First occurred: 18:10:07 (1 occurrences)
Last logged: 18:10:07

'raspistill' was not found

:( no way..

**Comment by terryrankine** [comment]
#same

0.118.1

**Comment by soterocra** [comment]
😢

**Comment by Xitee1** [comment]
Still no solution?

**Comment by agners** [comment]
No solution, see more details: https://github.com/home-assistant/core/issues/51755

**Comment by RubenKelevra** [comment]
@agners I mean, can we please leave the tickets open as long as this is a limitation?
