### ISSUE TITLE
HassOS on Synology DSM

### ISSUE THREAD

**Issue by coldi2k3** [home-assistant/hassos#131]
Heyho..

tried to install it on my Synology DSM.. Got the same problem as other ppl with BIOS and UEFI.. that got fixed quickly.. 

but after that, i get to the bootmenu, i can select something and then it just freezez up or does nothing at all.. only the 4th option with the shell worked... any ideas?

**Comment by schmidi198** [comment]
Hi

I have the same issue and i can confirm, that it does not work in Synology DSM with Virtual Machine Manager. See image below.

<img width="574" alt="screenshot 2018-07-27 um 19 12 18" src="https://user-images.githubusercontent.com/35111951/43336380-04700aa2-91d1-11e8-97e4-8ea435c9e9c8.png">

**Comment by bagobones** [comment]
It is possible to boot now in 1.12 with the IDE drive and a VirtIO NIC and USB 3 enabled.. Doesn't look like VirtIO works for the disk controller however.
