### ISSUE TITLE
Rpi_rf addon issues

### ISSUE THREAD

**Issue by adas4190** [home-assistant/hassos#136]
Hi. 

I cannot start that addon due to an error related to gpio. Is there any fix? I have tried both 32 and 64 version of the system and error persist. I use rpi 3b. Thank You

**Comment by JakobTewes** [comment]
Same issue here. Already tried adding "dtoverlay=pi3-miniuart-bt" to "/mnt/boot/config.txt" without luck. Thread for reference: https://community.home-assistant.io/t/homematic-occu-gpio-permission-denied/60371

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassio-addons/pull/364
