### ISSUE TITLE
GPIO doesn't work

### ISSUE THREAD

**Issue by kwdavidson** [home-assistant/hassos#141]
Running a Raspberry Pi 3 with [PiFace Digital 2 board](https://www.home-assistant.io/components/rpi_pfio/). All I/O works fine running Hass on top of resinOS. When running the same version of Hass on top of HassOS, no direct I/O can be accessed.

**Comment by pvizeli** [comment]
Without any kind of logs, I can't help. I can only say that we run the origin firmware of raspberry and maybe you need active some overlays. ResinOS have some overlays default enabled, but we have only the basic active and user need self activate what he need on "config.txt".

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassio-addons/pull/364
