### ISSUE TITLE
I/O errors with disk on 1.9 - esxi 6.5

### ISSUE THREAD

**Issue by mjburton** [home-assistant/hassos#154]
Hi,

I've got a VM to start and prompt for the HassIO boot menu - selecting Shell and 'boot system0'

However, as the boot process continues the VM will crash with an I/O error on sda7 and move to read-only.  Perhaps I've not added the hard disk correctly - it came up as a 6GB disk but then also recognised as a 142.81GB thick provisioned.  I suspect this is the issue and I need to configure the correct options.  Could anyone offer any suggestions?

Thanks

**Comment by KangKai1982** [comment]
Same issue here. 
EXSi 6.5U1
hard drive configed as IDE mode.
