### ISSUE TITLE
Waiting for root filesystem on boot with VMWare

### ISSUE THREAD

**Issue by nhorvath** [home-assistant/hassos#159]
Downloaded fresh 1.9 image. Created new 64 bit vm, 2 cores 1 GB ram and used the drive image downloaded. Tried to boot and got stuck at boot menu, saw another issue about deleting the CDROM. So I deleted CDROM and Floppy, then it let me pick System 0 and started to boot but gets stuck waiting for root filesystem.

![image](https://user-images.githubusercontent.com/165084/44002235-b39aa940-9e0d-11e8-8cfa-29d1a3f13c1a.png)

**Comment by mshrem** [comment]
Change the disk mode to SATA worked for me ....

**Comment by pvizeli** [comment]
Yes, we should also add other driver. What is the default disk driver?

**Comment by nhorvath** [comment]
Vmware is scsi by default

**Comment by pronsta** [comment]
I hope SCSI will be supported as its not working had to change to IDE with proxmox.
