### ISSUE TITLE
Integrate Resin Wifi Connect for easier network configuration

### ISSUE THREAD

**Issue by ndarilek** [home-assistant/hassos#167]
Seems like configuring wifi is the vast majority of what most users need pre-installation, and the USB configuration drive step is a bit cumbersome. Would it be possible to integrate something like Resin's [Wifi Connect](https://github.com/resin-io/resin-wifi-connect)? This brings up an AP on boot, then lets the user scan for networks and input a wifi connection via a web interface. Seems designed to run in a Docker container atop any distro that uses NetworkManager.

Maybe if no ethernet/wifi connection is detected after a certain point, Wifi Connect can be launched automatically?

**Comment by ProLoser** [comment]
I'm having trouble debugging my first raspi and it's erratic connection issues because I don't know for sure if my config worked. This would just get rid of my entire configuration headaches.
