### ISSUE TITLE
reporting /proc/cpuinfo? Maybe this breaks DHT Sensor

### ISSUE THREAD

**Issue by kaiomatico** [home-assistant/hassos#168]
Hey, if I'm in hassIO on hassOS and run cat /proc/cpuinfo on my Raspberry pi 3 b+ I only get the following Information: 
![image](https://user-images.githubusercontent.com/8037196/44408354-831d9e80-a560-11e8-8e70-a08e56d2df6a.png)

But the Adafruit DHT sensor uses the following code to check for the Raspberrypi version:
` # Anything else is not a pi.
    with open('/proc/cpuinfo', 'r') as infile:
        cpuinfo = infile.read()
    # Match a line like 'Hardware   : BCM2709'
    match = re.search('^Hardware\s+:\s+(\w+)$', cpuinfo,
                      flags=re.MULTILINE | re.IGNORECASE)
    if not match:
        # Couldn't find the hardware, assume it isn't a pi.
        return None
    if match.group(1) == 'BCM2708':
        # Pi 1
        return 1`
... etc ... (see this file: https://github.com/adafruit/Adafruit_Python_DHT/blob/master/Adafruit_DHT/platform_detect.py ) So maybe that is the reason why the DHT Sensors are no longer working.

Or am I wrong because I ran the command inside the hassIO container? If so I would like to know how to run a command directly on the host and what output from /proc/cpuinfo is returned there.

Thanks in advance!
Cheers, Kai

**Comment by pvizeli** [comment]
This is only on 64bit, my Rpi have this inside
