### ISSUE TITLE
Let's Encrypt add-on and Odroid C2 (beta)

### ISSUE THREAD

**Issue by iuro** [home-assistant/hassos#179]
Cannot renew the cert. Paths seems to be wrong.

Snippet from log (replace my domain with generic host.yourdomain.com)

starting version 3.2.4
Saving debug log to /var/log/letsencrypt/letsencrypt.log
-------------------------------------------------------------------------------
Processing /data/letsencrypt/renewal/host.yourdomain.com.conf
-------------------------------------------------------------------------------
expected /data/letsencrypt/live/host.yourdomain.com/cert.pem to be a symlink
Renewal configuration file /data/letsencrypt/renewal/host.yourdomain.com.conf is broken. Skipping.
-------------------------------------------------------------------------------
No renewals were attempted.
Additionally, the following renewal configuration files were invalid: 
  /data/letsencrypt/renewal/host.yourdomain.com.conf (parsefail)
-------------------------------------------------------------------------------
0 renew failure(s), 1 parse failure(s)

**Comment by rbray89** [comment]
was this on a clean install? Or did you migrate anything from another install?

**Comment by rbray89** [comment]
Any update?

**Comment by iuro** [comment]
Removing the add-on and reinstalling resolved the issue.

**Comment by rbray89** [comment]
Closed-per comment. An issue should probably be created for HassIO for backup and restore.
