### ISSUE TITLE
No network traffic when booting up hassos on Raspberry Pi 2

### ISSUE THREAD

**Issue by milesking** [home-assistant/hassos#181]
I have a Pi 2, which can boot Raspbian. After flashing hassos 1.9/2.1, boot process was stuck at "connection is ready". And no network traffic monitored by router.

**Comment by pengshp** [comment]
Hi, I have the same problem with you. Do you have solved it?

**Comment by milesking** [comment]
Nope, I tried Shadowsocks global proxy on the router, and monitored 8MB data for one hour. Hope it works. 
If failed, I'like to try shell post at bbs.hassbian.com. Installing hass on Raspbian.

**Comment by andrewcr7** [comment]
I'm seeing similar problem on 1.10 also with a Pi2.  Using wired network, works fine booting other OSes, but it doesn't appear to get even get an IP under hassos.
