### ISSUE TITLE
First boot up issue caused by NTP server

### ISSUE THREAD

**Issue by milesking** [home-assistant/hassos#183]
Hi guys, I'm in China. We can't access Google NTP Server (time1.google.com stuff). Since Raspberry PI's local time is not correct, SSL Certificate failed when downloading the image. Could you please change NTP server from Google to ntp.org stuff?
Thanks!

**Comment by fliaping** [comment]
@milesking you can add a hosts record: `<ntp server ip> time1.google.com` , by the way I use aliyun ntp `203.107.6.88    time1.google.com`

**Comment by mkh595** [comment]
@fliaping Where this can be added?

**Comment by milesking** [comment]
You can run Raspbian with GUI，then install hassio，quite easy with script. Running well for 3 month till now.

**Comment by pvizeli** [comment]
You are also able to set now NTP with HassOS.

**Comment by fliaping** [comment]
> @fliaping Where this can be added?

`vi /etc/hosts`

**Comment by truglodite** [comment]
> You are also able to set now NTP with HassOS.

How?
