### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by Partizan7676** [home-assistant/hassos#185]
Whatever i do... still get that error when i try to connect to new installation. USB-stick is OK - create profile for wireless connection and get RPI connect to my network. But hassio.local:8123 is not reachable - get message "connection refused". But ping by name is ok. What i do wrong?

**Comment by Fusseldieb** [comment]
Same here

**Comment by pvizeli** [comment]
Are you look the google ntp servers? without time, the device will be never setup. But you can access to terminal to see what is going on.

**Comment by Partizan7676** [comment]
@pvizeli any connection is refused(web, ssh). i only able to use an old image - it contain "resinos" in it's name - works greatly, Hassio updates to latest ver.
