### ISSUE TITLE
HassOS missing ffmpeg?

### ISSUE THREAD

**Issue by rbflurry** [home-assistant/hassos#186]
Is HassOS missing ffmpeg or do I need to install it somehow?

```
Log Details (WARNING)
Thu Aug 30 2018 19:16:23 GMT-0400 (Eastern Daylight Time)

FFmpeg isn't running!
```

**Comment by Joeboyc2** [comment]
What version of hassos are you running?

I started on 1.2 and it was present there and has continued working since

**Comment by rbflurry** [comment]
Im on 1.3.1 However I am running the VMDK if that makes a difference?

**Comment by pvizeli** [comment]
No, ffmpeg is available, look at hassio-homeassistant repository

**Comment by rbflurry** [comment]
Looks like ffmpeg is crashing with the ARLO component or video playback.
