### ISSUE TITLE
Asus Tinkerboard S or Odroid C2 with eMMC for hassio/hassos?

### ISSUE THREAD

**Issue by felixstorm** [home-assistant/hassos#187]
I would like to migrate my hassio/hassos from RPi 3 to a similar platform that is still future-proof with regards to hassio/hassos, but with a bit more (especially disk) performance, so has anyone a recommendation (maybe even @pvizeli) on whether I should buy an Asus Tinkerboard S or an Odroid C2 with eMMC module (or maybe even something completely different in a similar price range) for that purpose?

Thanks,
Felix

**Comment by felixstorm** [comment]
Sorry for being a bit off topic here (in the community forums most topics about Odroid do not yet target hassos but still resionOS or manual installations) and I know that there is no scientifically correct answer here - I was just hoping for personal opinions from people that have worked with several options...

**Comment by billchurch** [comment]
Any word on how you can implement eMMC on an existing HassIO on a Tinkerboard S?

**Comment by rbray89** [comment]
@billchurch It should be in the latest pre-release: https://github.com/home-assistant/hassos/releases/tag/2.4

**Comment by billchurch** [comment]
@rbray89 gotcha, so it's just a re-flash? nothing special to utilize the emmc?

**Comment by rbray89** [comment]
@billchurch Yeah, just treat is as an SD card. The bootloader script will take care of the rest.

**Comment by billchurch** [comment]
awesome, thanks!

**Comment by felixstorm** [comment]
@rbray89 Thanks, good to know.

After the governor had been fixed, the performance of my RPi became *a lot* better, so I did not do any migration yet.
