### ISSUE TITLE
time incorrect at first boot (hassos on esxi)

### ISSUE THREAD

**Issue by pergolafabio** [home-assistant/hassos#206]
hi, my time is correct in bios.-/esxi, but at first start of hassos, the time is  hour ahead, since i live in ETA +1 zone

so my sensors are not working for the first hour :), so when i do a clean boot, i need to restart hass when its loaded, afterwards it has the correct time

thnx

**Comment by highground88** [comment]
I think it's becuase HassOS seems to use UTP time, regardless of your time zone. 

I personally hope this gets changed, otherwise I'll need to move back to another OS.

**Comment by pergolafabio** [comment]
well, updated newer build, still same issue
but i dont care, i know when i do a cold reboot, i need to restart HA from the configuration one time after first start
