### ISSUE TITLE
Wish: Clear Build Tutorial

### ISSUE THREAD

**Issue by zerolith** [home-assistant/hassos#22]
Hi, I'd like to build this, but the instructions are not clear (for me).

- About the USB Stick & hass.json, how, and when does this get used?
- The line: make -C /build/buildroot BR2_EXTERNAL=/build/buildroot-external xy_defconfig isn't doing anything for me.
- How to actually get an Image for a RPI?

thank you!

**Comment by pvizeli** [comment]
That is a simple buildroot envoriement: https://buildroot.org/downloads/manual/manual.html
