### ISSUE TITLE
Unable to access host through SSH

### ISSUE THREAD

**Issue by robbinjanssen** [home-assistant/hassos#225]
I am trying to access the host system via SSH (port 2222). I've followed all instructions on the [Debugging Hass.io](https://developers.home-assistant.io/docs/en/hassio_debugging.html) page but have not been able to login. I'm using the same key as I'm using for the port 22 connection with the SSH addon, so the key is not the problem. Any tips? Is there any specific log message I need to see when I import from USB?  

Note; my USB stick is named "CONFIG", it is formatted as FAT and only has the `authorized_keys` file on it. Key and `authorized_keys` file have been created on a macbook using the terminal.

**Version:** HassOS 1.11

**Comment by robbinjanssen** [comment]
Okay, i'm stupid, trying to connect to port 2222 instead of 22222.

Shame on me!

**Comment by mhaas** [comment]
@robbinjanssen Four years later, I find this issue. Exact same problem here - PEBKAC. Thanks for sharing!
