### ISSUE TITLE
Improper time zone in configuration.yaml prevents start of hassio

### ISSUE THREAD

**Issue by amayii0** [home-assistant/hassos#242]
Hello,

I'm using the hassos_rpi2-1.12.img image.
Initial startup went just fine, great.
I tried to setup the time_zone under configuration.yaml / homeassistant:time_zone

Config file points reader to https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
I'm living in Belgium, so I used the BE code. That somehow wasn't properly handled.
I had to use SSH access to modify configuration file and turn it back to UTC.

I retried using value from TZ column (Europe/Brussels) instead of CC column (BE) and it went just fine.
Please make comment in configuration.yaml more explicit.

While busy improving comments.
Why not add a link to a site to get latitude/longitude like http://zip-code.en.mapawi.com/belgium/15/bruxelles/1/3/bruxelles/1000/1/ ?

Regards

**Comment by pvizeli** [comment]
Do you speak about the start of Home Assistant or Hass.io aka Supervisor?

In the case of the supervisor, can you post the error log?
In the case of Home Assistant, we need to move this issue to this repository.
