### ISSUE TITLE
get RAUCB files for the OTA

### ISSUE THREAD

**Issue by sholzmayer** [home-assistant/hassos#249]
I'm able to build the `hassos_rpi3-64-1.xx.img.gz` by myself using the `build-all.sh` with the instructions from the docs. 

But in the end i just have the `hassos_rpi3-64-1.xx.img.gz` in the releases folder. How can I build the `hassos_rpi3-64-1.xx.raucb` file or where can i find it after the `build-all.sh` finishes?

Thank you

**Comment by pvizeli** [comment]
That's not possible. Only core/project developers have a Cert to generate OTA update packages.

Users with a Cert can make OTA updates they can install an update and inject code to other persons. So it needs a trust to this users.

Provide code grow up to an official project developer :)

**Comment by sholzmayer** [comment]
okay I just was wondering why this step was skipped. Maybe a warning message would be cool, that this step is skipped :)
