### ISSUE TITLE
find command not available

### ISSUE THREAD

**Issue by cogneato** [home-assistant/hassos#250]
It looks like it is set here?
https://github.com/home-assistant/hassos/blob/3c21a8c486870c8da14e09fa331fdae7679df4eb/buildroot/package/busybox/busybox.config#L432

But it is not available when connected to the host.

**Comment by jvanderneutstulen** [comment]
There are two issues here:

1. When you login via hassos-cli, it does not run ash as login shell, so `/etc/profile` will not be read and `/usr/sbin` is added to the $PATH.
2. The actual busybox config is set from `buildroot-external/busybox.config` and does not enable the find command.

**Comment by pvizeli** [comment]
@jvanderneutstulen we should fix the path on the hassos-cli script before we map the host shell
