### ISSUE TITLE
RPI 3b+ cannot install hassio

### ISSUE THREAD

**Issue by boaschti** [home-assistant/hassos#264]
Hi
My rpi hangs after a short time during install process.
First everything looks fine red led is on and green led flashes as usual.
Ping is Ok.
Then red and green led is on, Pi gets warm, no ping is possible. No reaktion after hours...
I use etcher, raspian and a other image (homeassistant) are running.
I tried hassos_rpi3-1.11, hassos_rpi3-1.12, hassos_rpi3-1.13, hassos_rpi3-2.3.
Any idea??

https://community.home-assistant.io/t/fresh-install-on-raspberry-pi-3-b/61836/28

**Comment by pvizeli** [comment]
Can you attach an HDMI and look what you see? Maybe you can log in and use `su logs` or `journalctl -f` on shell itself.

**Comment by boaschti** [comment]
Here a photo. I think login is not possible.

![photo_2018-11-28_16-10-10](https://user-images.githubusercontent.com/16265092/49160964-30eed500-f328-11e8-9c15-c2200794f265.jpg)

**Comment by mkh595** [comment]
It looks as same place as #246 
Did you try file timesyncd.conf with NTP servers?

**Comment by boaschti** [comment]
Really no boot without ntp??? Ist it fixed in comming versions? Is rtc with auto detect an option? Looks exact the same. Can you explain what is to do?

**Comment by ajdezigns** [comment]
Can someone please loop me in on what to do with the "timesyncd.conf" as in what it is and where i put/ alter it?? I'm having the same issues

**Comment by boaschti** [comment]
I don't know it yet. I was in hope that future image versions (2.4) are working... It is a little bit annoing for beginners or “not linux people“ to fail with the official “get started“ installation.

**Comment by jvanderneutstulen** [comment]
Please try the new 2.5 image, it should use hardware random device, which will improve https performance at boot time quite a bit.
Timesyncd config is explained in https://github.com/home-assistant/hassos/blob/dev/Documentation/configuration.md.

**Comment by boaschti** [comment]
Following solution works for me:
Image 2.5.
Put following lines into a file named timesyncd.conf on a usb stick named CONFIG. Put the USB stick into your pi before powering on.
`[Time]
Servers=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org
`

@pvizeli 
Isn't it possible to put a valid standard file into the image?

**Comment by pvizeli** [comment]
There is a working file they read the time from Google. You can use your own time server with the CONFIG folder on boot partition or USB stick.

**Comment by boaschti** [comment]
Yes but then there is another problem with the timeserver. Google is definitely reachable in my network.
