### ISSUE TITLE
NetworkManager not working in access point mode

### ISSUE THREAD

**Issue by bannhead** [home-assistant/hassos#276]
Either via configuration upload from usb or via nmcli in console mode, it's not possible to set access point mode. 
When trying to enable the connection (nmcli c up _connection_id_) return this: 

> Error: Connection activation failed: No suitable device found for this connection.

Networkmanager is working normally using infrastructure or adhoc mode.

I have not found any reference on NetworkManager development site, but maybe updating to a recent version could resolve the problem.

**Comment by pvizeli** [comment]
Yeah, I will update the version. But I would have no time for this task. Maybe with next developer tree v4.
