### ISSUE TITLE
host system port 10010

### ISSUE THREAD

**Issue by sholzmayer** [home-assistant/hassos#284]
I found out, that the port `10010` is open on the hassos system responding with `404: Page Not Found`. I cannot find it anywhere in the hassOS or hassIO source-code. Also there is no docker service using this port.

Any idea to which service this port belongs and for what it is needed?

**Comment by Eisler** [comment]
Looks like a docker problem fixed in docker version 18.06.1 . https://github.com/containerd/containerd/issues/2483

**Comment by pvizeli** [comment]
I closed on dev
