### ISSUE TITLE
Configure multiple wifi AP

### ISSUE THREAD

**Issue by naidu** [home-assistant/hassos#287]
I could configure the wifi ap following the documentation at https://github.com/home-assistant/hassos/blob/dev/Documentation/network.md .  

Is is possible to configure multiple ap using the config file?  One for office wifi and one for home?

**Comment by jvanderneutstulen** [comment]
Using a separate file for every wifi network should work. Just make sure you use a unique id and uuid.

**Comment by naidu** [comment]
It works.

**Comment by CuriouslyCory** [comment]
I can't get this working using the raspberry pi 3b+ image. I tried using the usb stick method as well as using the CONFIG folder on the boot partition method. The only way I've got this working is by using a keyboard and configuring via nmcli.
