### ISSUE TITLE
HassOS .5 doesn't get past "preparing hassio" screen

### ISSUE THREAD

**Issue by cogneato** [home-assistant/hassos#30]
The last line I see is
`IPv6: ADDRCONF(NETDEV_CHANGE): hassio: link becomes ready`

**Comment by danielsjf** [comment]
Haven't tried the 32bit version yet, but  for the 64bit version, the behaviour seems the same as yesterday. Black boot screen and no ip coming online.

**Comment by danielsjf** [comment]
For Rpi 3 model B+

**Comment by danielsjf** [comment]
Tried the 32bit with rpi 3 model B+. Booting works, but I get the same result as the OP.

**Comment by pvizeli** [comment]
Will be fix with 0.6

**Comment by tjorim** [comment]
Confirmed for me, can the issue be closed?

**Comment by pattyland** [comment]
Is 0.6 a future releays HassOS Release 1 or is 0.6 the beta version?

I get this error everytime I boot my HassOS Release 1 build 5 in ESXi :(

**Comment by pvizeli** [comment]
That is not a error, it's only a kernel message

**Comment by pattyland** [comment]
@pvizeli Thanks for the info, the problem was a not supported network adapter

**Comment by DevinCook** [comment]
I had the same issue with a 16G card, switched to 32G and it booted.
