### ISSUE TITLE
Any sort of TCP ratelimiting on hassos?

### ISSUE THREAD

**Issue by funkypenguin** [home-assistant/hassos#311]
Hi all,

I'm trying to debug an issue whereby my HA instance (on hassos) will stop talking to my DAFANG cameras, as soon as I enable mqtt services (for status and control) from the DAFANGs.

The symptoms of the issue are that all containers on hassos stop being able to communicate with the DAFANGs after a period, and it's only a full reboot of hassos which restores the expected behaviour.

My theory is that this has to do with the excessive amount of MQTT sessions the DAFANGs establish with the MQTT service, running in a docker container on hassos.

Is there any default limit applied to TCP sessions at the hassos level, which might prevent further communication with an IP which has recently attempted lots of connections to a port exposed by the MQTT container?

Thanks!
D

**Comment by pvizeli** [comment]
There is no limit from HassOS. Can you try an upstream developer version?
