### ISSUE TITLE
Failed services when shutting down HassOS (Orange Pi Prime)

### ISSUE THREAD

**Issue by deece** [home-assistant/hassos#314]
When shutting the machine down with `poweroff` on the console, the following services fail:
```
[FAILED] Failed unmounting NetworkManager persistent data.
[FAILED] Failed unmounting Systemd persistent logging.
[FAILED] Failed unmounting HassOS ZRAM var.
```

It would be interesting to see if this occurs on other platforms

**Comment by jvanderneutstulen** [comment]
Yes, probably because NetworkManager leaves dhclient running when it exits.
