### ISSUE TITLE
Orange Pi Prime: Relatively slow kernel loading time vs Armbian

### ISSUE THREAD

**Issue by deece** [home-assistant/hassos#317]
It takes ~9 secs to load the kernel for HassOS, but ~1second for Armbian, @deece to investigate why.

HassOS:
20144640 bytes read in 11188 ms (1.7 MiB/s)

Armbian:
8781859 bytes read in 445 ms (18.8 MiB/s)
14243848 bytes read in 713 ms (19.1 MiB/s)

**Comment by jvanderneutstulen** [comment]
The Hassos kernel has almost everything compiled in, so has probably more to do.

**Comment by pvizeli** [comment]
Yes, all kernel modules they we anyway need on runtime is compiled in. That makes docker faster startup.

**Comment by deece** [comment]
That's not the problem, the sizes are similar, but the throughput is an order of magnitude different

**Comment by jvanderneutstulen** [comment]
This comment, https://github.com/madisongh/meta-tegra/issues/42#issuecomment-323536525, in [u-boot: eMMC transfer speed significantly slower than stock u-boot on Tegra186](https://github.com/madisongh/meta-tegra/issues/42) is interesting.
Maybe running `mkfs.ext4` for the the kernel image with `-O ^extent` will help in our case.

**Comment by pvizeli** [comment]
Can we do, it's only a small partition of 24mb

**Comment by jvanderneutstulen** [comment]
Use `-O ^extent,^64bit` with our toolchain. Didn't notice any difference on a rpi3 with sdcard though.

**Comment by deece** [comment]
I'm currently travelling,. But will investigate when I get home.
