### ISSUE TITLE
Hardware Donation

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/hassos#33]
To support more device, we need more Hardware. I live in Switzerland and our prices and duties (especially import) are high.
If you have a device which you don't need anymore and will send us or you want donate a small amount for a device, that would be amazing. Feel free to extend this list of hardware.

You can send donation to my paypal account and add a description with the name of you favorite device.

## Hardware list
- ~~ASUS Tinker Board: 70$ - 100%~~
- Pine64: 30$ - 0%
- ~~Rock64: 50$ - 100%~~
- ~~Raspberry Pi 3+: 50$ - 100%~~
- ~~Intel nuc: 130$ - 100%~~
- ~~Orange Pi PC 2: 28$ - 100%~~
- ~~Orange Pi Zero: 18$ - 100%~~
- ~~Orange Pi Zero 2: 28$ - 100%~~
- Odroid C2: 70$ - 0%
- ODROID-HC2: 75$ - 0%
- ~~Odroid XU4: 85$ - 100%~~

Paypal: pascal@vizeli.ch / http://paypal.me/pvizeli
Patreon: https://www.patreon.com/pvizeli
For post address, send me a PM on discord.

**Comment by ciotlosm** [comment]
Any chance to add some Orange Pi models as well?

**Comment by pvizeli** [comment]
What kind of OrangePi make sense?

**Comment by ciotlosm** [comment]
Probably Orange Pi Zero and Orange Pi PC 2. One is a H3 and one is H5. I have the Orange Pi PC 2 but don't know what is currently most popular, as most custom builds used Orange Pi Zero

**Comment by danielsjf** [comment]
You should have a Patreon account!

**Comment by CountParadox** [comment]
I would support a homeassistsnt patreon account tbh

**Comment by dzungpv** [comment]
You can add a donate button on the home page, and anyone can send you optional 5, 10, 15, 20 ... until you can purchase all the hardware you can simple close, or just let it there. I will donate 18$ for Orange Pi Zero

**Comment by ciotlosm** [comment]
If anyone wants to Donate using Revolut, you can ping me and then I can proxy them to pvizeli as well.

**Comment by pvizeli** [comment]
patreon account is in progress

**Comment by bboti86** [comment]
Might be far fetched but have you considered one of these: 
https://getchip.com/pages/chippro#undefined4

**Comment by pvizeli** [comment]
https://www.patreon.com/pvizeli

**Comment by rudders** [comment]
I’ve Patreoned $5/mnth and will let it roll for 12 months at least so use that as you choose.

**Comment by CountParadox** [comment]
I patreon $10 a month, please continue your hard Dev work ❤️

I have run into a Hass.io but with USB serial devices now :( I'm hoping
it's fixed in a future version

**Comment by pvizeli** [comment]
@CountParadox make a PR. I run devices over GPIO and usb/serial without problems...

**Comment by olskar** [comment]
@pvizeli Will you need testing? I own a Rock64 and can test if needed :)

**Comment by pvizeli** [comment]
@olskar I order now a rock64. I need no tester ;) We need porting the bootloader to our system...

**Comment by bboti86** [comment]
@pvizeli: would one of these help with serial debugging: http://www.ni.com/hu-hu/shop/engineering-education/portable-student-devices/myrio-student-embedded-device/what-is-myrio.html ? 
It has an FPGA that could read serial transmission in real time and you could process that on your PC. 
Let me know

**Comment by jlbphotos** [comment]
Donated 68 dollaroos to the NUC
Will add to next month if i can as well, thanks for all the hard work.

**Comment by okueng** [comment]
@pvizeli  dontated 40CHF for the intel nuc via paypal!

**Comment by mad-ady** [comment]
Odroid HC2 runs the exact same software as the XU4, so if it runs on XU4 it will run on HC2 as well. I have both so I can test them if needed.

**Comment by pvizeli** [comment]
@mad-ady they have also a SD slot for OS?

**Comment by mad-ady** [comment]
XU4 supports both SD or eMMC (has a selector switch). HC1/HC2 (and MC1) have only SD slot (and HC1/HC2 have SATA for a hard drive). Note that it still needs the SD card to boot (boodloader can't be on SATA), but rootfs can be moved to disk if needed. Not sure if uboot can read kernel/initrd/dtb from SATA - all the examples I've seen do it from the SD and after kernel boots it can mount the rootfs from SATA.

**Comment by jlbphotos** [comment]
Got paid...just paid 26 Euro for the NUC hopefully that's 100% now

thanks

**Comment by frog32** [comment]
Sent CHF 50 your way. Use it for whatever you need besides just boards (SD cards, ethernet cables, power adapters).

**Comment by ciotlosm** [comment]
@pvizeli do you need anything extra to help with automation of deployments/testing?

**Comment by gotodragon** [comment]
@pvizeli I test hassos ver 1.7, it is same with ver 1.5, no data transfer.

**Comment by dzungpv** [comment]
BeagleBone Black is the board often use by professional,with fast emmc flash, any change you will make hassos work with it?

**Comment by ciotlosm** [comment]
@dzungpv if you start some donation for it probably will get added to the list so others can help support it.
