### ISSUE TITLE
hyper-v hassos vhd - update to latest version

### ISSUE THREAD

**Issue by lpt2007** [home-assistant/hassos#333]
How to upadte hassos 2.4 to 2.6 (latest vesrion)?

I try under `HASS.IO -- SYSTEM - UPDATE` but not working.

**Comment by meichthys** [comment]
@lpt2007 

Are there any errors in the logs? It's hard to help out if we don't know what errors you're seeing. I was having a similar issue. A few items to check:

- Have you turned off SecureBoot for the HyperV VM?
- Have you tried turning off dynamic memory for the VM?

Those were two items which i found were causing issues with my Hassos when trying to reboot.

**Comment by lpt2007** [comment]
Hi @meichthys 

> Have you turned off SecureBoot for the HyperV VM?
> Have you tried turning off dynamic memory for the VM?

I have both settings turned off .

After I press `HASS.IO -- SYSTEM - UPDATE` vm goes to reboot and stays on:

```
PXE Network boot using IPv4 ( ESC to cancel )
Preforming DHCP Negotiation ................

```

**Comment by meichthys** [comment]
@Ipt2007

Have you tried spamming the ‘m’ key when it boots?

You should be able to get to the boot menu and choose which volume to boot from. This worked for me. I still do have issues rebooting sometimes, but I find that the most reliable way to reboot is to shutdown the vm from hyperv itself and then start the VM from hyperv.

Hassos still needs some work to be compatible with Hyperv, but we are getting there...

**Comment by meichthys** [comment]
I  I honestly cannot remember how I got mine upgraded to 2.6, but you could try:

- upgrading from the Hassos command line using command: “os update” (you may also want to run: “host update” before)

One thing I’ve noticed is that the web GUI takes a while to be available after reboots. Usually it will come up eventually, but it can take quite a while. As weird  as it may sound, it sometimes seems to help if I login to the hassos command line while waiting for the GUI to be available. (This isn’t an option if you’re still stuck on the boot screen)

**Comment by lpt2007** [comment]
> upgrading from the Hassos command line using command: “os update” (you may also want to run: “host update” before)

How to get to commandline?

I try on ssh adddon, but not working. `os update` command not found?

**Comment by YellowGTO** [comment]
You get to the command line by hitting enter in the VM window. But os update doesn't seem to work for me. I had the same issue with having to spam m.

![image](https://user-images.githubusercontent.com/13971492/51803818-3d5bb500-2227-11e9-90b1-21793d069972.png)

**Comment by lpt2007** [comment]
Thanks @YellowGTO.

Let me know if you find out how to update.

**Comment by meichthys** [comment]
@YellowGTO  Thanks for the info!

Also, i'm not sure if the "Reboot" button under Configuration>General>ServerManagement>Reboot works for you, but it just seems to hang for me. (Same with the HASS.io>System>Reboot option).

What does work for me when rebooting is to run the "ho reboot" command from the terminal. I'm not sure why that would be any different, but running it from the terminal reboots super fast.

**Comment by lpt2007** [comment]
> pvizeli informed me: SSH in and run
> curl -d '{"version": "2.6"}' -H "X-hassio-key: $HASSIO_TOKEN" http://hassio/hassos/update

I get error when I try to run this from ssh:
pvizeli informed me: SSH in and run
![error_on_update_hyperv](https://user-images.githubusercontent.com/38924279/52175988-d8ff9f00-27ac-11e9-9362-a74b1dd1f2f0.jpg)

**Comment by lpt2007** [comment]
I added 2.7 under version and I can udate now. I try from 2.4 and 2.6 👍 
`curl -d '{"version": "2.7"}' -H "X-hassio-key: $HASSIO_TOKEN" http://hassio/hassos/update`
