### ISSUE TITLE
Issues trying to take advantage of ability to move hassos-data filesystem to separate device

### ISSUE THREAD

**Issue by TonyApuzzo** [home-assistant/hassos#343]
Seems that booting HassOS Dev 3.0 with a relocated hassos-data doesn't always work -- at least on my ODroid HC1, even after [PR#318](https://github.com/home-assistant/hassos/pull/318)  Mentioning @berg since he is author of PR#318.

I wasn't sure if it warranted a new issue, so I commented on the PR, but that was not the correct process, so I created this issue.

For kernel logs and work so far see:

* https://github.com/home-assistant/hassos/pull/318#issuecomment-460028839
* https://github.com/home-assistant/hassos/pull/318#issuecomment-460029474

**Comment by berg** [comment]
Gotcha, thanks. I think that the errors you saw from attempts one and two were related to not swapping around the partitions properly; let's focus on the partially successful attempts three and four.

The flakiness you're seeing isn't too far from what I'd originally seen—which was the original motivation for this patch—so this is a bit concerning. It does look like you've successfully managed to pull in the PR, so that's good.

Any chance that—when it fails—you can provide a complete boot log? I think there's something failing earlier in the boot when you get to

>[DEPEND] Dependency failed for HassOS data partition.

... but it's not included in the logs, so being able to see all the way back to the first line the kernel prints would be helpful.

**Comment by TonyApuzzo** [comment]
Full logs are uploaded here, note that I copy/pasted from the serial console so it is possible there are some transcription errors:

* [Boot failure](https://gist.github.com/TonyApuzzo/48d47a66badeb2e9797826d1c9b1f714#file-hc1_fail-txt), when this happens I can still ping the device but can't get a shell or any other response.
* [Boot success](https://gist.github.com/TonyApuzzo/48d47a66badeb2e9797826d1c9b1f714#file-hc1_good-txt), no system changes, just powercycled after the above failure and it worked.

Wild speculation: It seems if I wait a while ~10 minutes??? the next boot works usually but if I reboot quickly after the hang then it does not.  Wondering if there is an fsck or resize operation still doing something in the background and waiting for that to complete even though there are no logs allows the next boot to work???

**Comment by jvanderneutstulen** [comment]
failed:
`[ 16.942218] usb 4-1: New USB device found, idVendor=152d, idProduct=0578, bcdDevice=31.01`
versus good:
`[ 5.614275] usb 4-1: New USB device found, idVendor=152d, idProduct=0578, bcdDevice=31.01`

Apparently your usb-disk takes  a nap sometimes. So the reason it sometimes works is related to your hardware. We could wait longer for the mount to become available. Also some services do startup after the mount is available, like NetworkManager and other do not, like getty and ssh.

**Comment by TonyApuzzo** [comment]
I am playing around with naive sleeps and polling loops in the hassos-expand script but it takes 20-30 minutes per test cycle with my current workflow so progress is slow.

Did some googling and ran across [this problem report](https://forum.odroid.com/viewtopic.php?f=99&t=29615) which got me thinking that maybe I do have a power problem -- especially since a couple times on boot it didn't recognize the network adapter, which I had been thinking was unrelated.

I have the ODroid 4A supply, but maybe I should've bought the 6A.

**Comment by TonyApuzzo** [comment]
So far my kludges in hassos-expand have not helped, but I am a total systemd newb so it is very likely I am doing something stupid in there since the sleeps don't seem to be having any effect.  Once I figure out logging I will try again to debug.

I ordered a higher power supply and a much newer model SATA SSD (Patriot Burst 240GB, only $30), so I will have some extra hardware to play with in case that is a better solution.  The SSD will be here Friday but the power supply will be a week or so.

**Comment by berg** [comment]
It should wait 90s before giving up on your disk—I'm more worried I've got the dependencies for the `hassos-expand` target set incorrectly or there's a bad interaction here.

@TonyApuzzo would you mind building this branch:

https://github.com/berg/hassos/tree/berg-test-expand

And capturing some logs if it fails/works? It is just adding extra logging, so I do not expect a behavior change (but it is build off current HEAD, so there may be other changes).

**Comment by TonyApuzzo** [comment]
Thanks for the update, I will try it as soon as I can, might be a day or two.

**Comment by TonyApuzzo** [comment]
Curiouser and curiouser... it seems the behavior has changed with the latest pull.

I can't get the resize to work at all anymore.  It is corrupting the data partition on SSD.  I tried several times and it failed with the same error each time [failure gist](https://gist.github.com/TonyApuzzo/b6cb594add8140c4c3a6348f5427348d).

However, if I manually resize the target partition to be full, then I get a good boot [success gist](https://gist.github.com/TonyApuzzo/07725536ec1a86a682aed30754adb11d)

Basic process as a recap:

1. recompile hassos from branch (berg-test-expand) via `make odroid_xu4` in my docker environment on windows
2. burn img to sdcard on build machine (windows)
1. mount ssd in odroid hc1
1. mount hassos sdcard in usb card reader on hc1
1. boot odroid hc1 using armbian sdcard
3. create empty large partition on ssd /dev/sdc1
4. `dd if=/dev/sda4 of=/dev/sdc1 bs=4M`
5. `e2label /dev/sda4 hassos-data-orig`
6. `e2label /dev/sdc1 hassos-data`
8. OPTIONAL MANUAL RESIZE: `e2fsck -f /dev/sdc1` `resize2fs /dev/sdc1`
1. shutdown armbian
1. remove armbian boot sd card from internal reader
1. remove usb card reader with hassos sd card
8. mount hassos sdcard in hc1 internal card reader
9. boot hc1
1. fail or good depending on whether or not I manually resized the partition

Note: The above logs are with a new SSD, I did attempt the same with my old SSD and I got roughly the same bad behavior with a simple dd copied (undersized) fs in a big partition.  The filesystem ended up corrupt although the specific error messages were different.  I will attempt to capture a trace of that as well but am running into some different problems duplicating the error now.

**Comment by TonyApuzzo** [comment]
And a couple more logs.  I think that I figured out why the old SSD is not recognized on boot, it does seem to be a power related issue.  If I mount the old SSD (m4) with a powered USB hub, then it is recognized always.  However, there is still some sort of race condition with the partition resizing and mounting.

WIth the external hub, the first time I boot up with the hassos-data partition copied, I get a straightforward [failure 5](https://gist.github.com/TonyApuzzo/842f1ccaa61bc57bf3f139459fff69bc)

If I reboot with the exact setup after the previous fails, then it boots to completion but I end up with a non-resized filesystem (1GB) and then hassio fails to provision itself since the FS is too small [failure 6](https://gist.github.com/TonyApuzzo/97c8f944503ac9fb5d326ca53fe20bec)

I'm done for now but hopefully these logs shed some light on what is happening.

**Comment by TonyApuzzo** [comment]
With the change that @berg made and with my new SSD, I have not had any mount failures, so I think the problems that caused me to create this issue have been addressed.
