### ISSUE TITLE
mi_water_purifier error

### ISSUE THREAD

**Issue by braverynew** [home-assistant/hassos#347]
After update hassos from 2.7 to 2.8. Hass can not connect to xiaomi mi_water_purifier, every xiaomi water sensors not available. Pls help
<img width="428" alt="screen shot 2019-02-07 at 11 29 31 am" src="https://user-images.githubusercontent.com/6349642/52390584-bed70100-2acb-11e9-883d-7833086cc0aa.png">

**Comment by carloscae** [comment]
Just updated to 2.10 and a bunch of components are now failing:

Arlo
Netatmo
Nello
Nest
