### ISSUE TITLE
Can't start web after _ho reboot_ on Pi3B

### ISSUE THREAD

**Issue by KKnishev** [home-assistant/hassos#350]
can't start web after _ho reboot_ on Pi3B
hostname: hassio
kernel: 4.14.81-v7
operating_system: HassOS 2.8
HELP PLEASE!!!

Log not from my system, but the same:
```
[   30.869545] kauditd_printk_skb: 26 callbacks suppressed
[   30.869556] audit: type=1400 audit(1545951108.100:65): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="hassio-supervisor" pid=3046 comm="apparmor_parser"
[   30.894461] audit: type=1400 audit(1545951108.100:65): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="hassio-supervisor///usr/bin/gdbus" pid=3046 comm="apparmor_parser"
[   30.915528] audit: type=1400 audit(1545951108.100:65): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="hassio-supervisor///usr/bin/git" pid=3046 comm="apparmor_parser"
[   30.936263] audit: type=1400 audit(1545951108.100:65): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="hassio-supervisor///usr/bin/socat" pid=3046 comm="apparmor_parser"
[   30.957165] audit: type=1300 audit(1545951108.100:65): arch=c00000b7 syscall=64 success=yes exit=68940 a0=6 a1=ffffb99b0010 a2=10d4c a3=0 items=0 ppid=3045 pid=3046 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="apparmor_parser" exe="/usr/sbin/apparmor_parser" subj==unconfined key=(null)
[   30.987601] audit: type=1327 audit(1545951108.100:65): proctitle=61707061726D6F725F706172736572002D72002D57002D4C002F6D6E742F646174612F73757065727669736F722F61707061726D6F722F6361636865002F6D6E742F646174612F73757065727669736F722F61707061726D6F722F68617373696F2D73757065727669736F72
```

**Comment by KKnishev** [comment]
![img_20190209_174536](https://user-images.githubusercontent.com/22073966/52522433-6c960b80-2c96-11e9-9756-6fbeafca8da3.jpg)

**Comment by pvizeli** [comment]
Log into host and post the logs of `su logs`, `ha logs`

**Comment by KKnishev** [comment]
Thanks for support @pvizeli, sorry for screenshots, don't know how to save files from Pi3.
su logs at screen
ha log is empty, it's down as I see
![img_20190211_213955](https://user-images.githubusercontent.com/22073966/52585592-3c8d6a80-2e46-11e9-837c-5a67f7196a01.jpg)

**Comment by jvanderneutstulen** [comment]
Is your HA config valid  (`ha check`) ?

**Comment by KKnishev** [comment]
hassio > ha check
**ERRO**[0000] Unexpected server response
Unexpected server response
hassio >

**Comment by pvizeli** [comment]
- `ha stop`
- `ha start`

**Comment by KKnishev** [comment]
hassio > ha stop
Error:

hassio > ha start
**ERRO**[0000] Unexpected server response
Unexpected server response

**Comment by KKnishev** [comment]
Сan this be related to this topic (AppArmor profile):
https://developers.home-assistant.io/docs/en/hassio_addon_security.html

**Comment by pvizeli** [comment]
do you see anything inside supervisor logs after you execute these commands? Home Assistant has no AppArmor profile.

**Comment by KKnishev** [comment]
Now yes!
![img_20190212_213906](https://user-images.githubusercontent.com/22073966/52659809-462ed500-2f0f-11e9-8f65-30984b1ea28c.jpg)

**Comment by KKnishev** [comment]
How and where find position 6494 ??
Here is a similar [issue](https://community.home-assistant.io/t/strange-errors-not-sure-how-to-troubleshoot/47969)

**Comment by KKnishev** [comment]
Unfortunately I could not restore it, reinstalled with backup. Thanks for support. Closed.
