### ISSUE TITLE
ring buffer patch needed for odroid_xu4

### ISSUE THREAD

**Issue by TonyApuzzo** [home-assistant/hassos#354]
In trying to copy between 2 USB drives on my ODroid HC1 (compatible with XU4) I ran into the same problem described here:
 
[2 USB3 Drives: mkfs slow, ring expansion failed dmesg error](https://forum.odroid.com/viewtopic.php?t=27973)

I created a test HassOS build using the referenced [patch](https://github.com/hardkernel/linux/commit/66d3985b4a0da52bbaf6da6d0a7b42890eef5b42.diff) and it seems to have solved the problem.

I don't know the correct process to apply a patch, but this looked like it worked (of course maybe I imagine it worked only, I don't know how to tell 100% that the patch is actually in the build I made). I can create a pull-request if desired, but all I did was exactly place the contents of the diff link above into 

```
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   buildroot-external/board/hardkernel/odroid-xu4/patches/linux/000-arm-exynos_change_the_default_dma_coherent_pool_size.patch
```

**Comment by pvizeli** [comment]
Yeah looks fine. You need only make a PR with this commit 👍
