### ISSUE TITLE
Instructions for USB boot

### ISSUE THREAD

**Issue by Ayo91** [home-assistant/hassos#358]
How can I boot the system using an external SSD?

**Comment by rbray89** [comment]
What platform?

**Comment by Ayo91** [comment]
Hass.io and HassOss

**Comment by rbray89** [comment]
No, I mean what hardware platform.

**Comment by Ayo91** [comment]
Ahh ok, sorry. Raspberry Pi 3B

**Comment by rbray89** [comment]
Unfortunately we can't boot from most embedded devices using USB. There is a thread [https://github.com/home-assistant/hassos/issues/164#](here) That I see you've already found that documents the same use-case.

The RPi3B+ is special though, in that you CAN permanently enable USB boot with a FW configuration mechanism, but our boot-loader simply isn't setup to handle that case.

**Comment by Ayo91** [comment]
ok, thanks. Is there any option to reduce the overload of the SD card and use together with an USB SSD in the Raspberry Pi 3B?

**Comment by talondnb** [comment]
> Unfortunately we can't boot from most embedded devices using USB. There is a thread [https://github.com/home-assistant/hassos/issues/164#](here) That I see you've already found that documents the same use-case.
> 
> The RPi3B+ is special though, in that you CAN permanently enable USB boot with a FW configuration mechanism, but our boot-loader simply isn't setup to handle that case.

So are you suggesting there are no plans to get USB/SSD boot working?

**Comment by tiagofreire-pt** [comment]
> The RPi3B+ is special though, in that you CAN permanently enable USB boot with a FW configuration mechanism, but our boot-loader simply isn't setup to handle that case.

That is only applicable on 3B, not 3B+, as the first one has a one time non reversible setting.
