### ISSUE TITLE
ODROID C2 : CPU temperature not reported anymore

### ISSUE THREAD

**Issue by lyazide** [home-assistant/hassos#366]
Since the last updates the CPU temperature is not reported anymore. I had it reported previously with the following sensor:

 - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'

/sys/class/thermal/thermal_zone0/ and so /sys/class/thermal/thermal_zone0/temp do not exist anymore.

**Comment by JSchoeck** [comment]
In newer kernel versions (3.8+) the location of the temperature files changed to /sys/devices/virtual/thermal/thermal_zoneX/temp - where the X is a value from 0 to 4.
