### ISSUE TITLE
HassOS 2.10 stuck at boot

### ISSUE THREAD

**Issue by tboyce021** [home-assistant/hassos#369]
I was previously running 2.9 and tried updating to 2.10 via the Hassio menu. It seemed to work, except that after rebooting it won't start up anymore. It appears to be the same issue as #344 but I'm running the VMDK with Proxmox on a NUC. I have my data partition moved to a separate drive, but the partition labels all look correct still. I've tried reboot the VM and NUC to no avail.

![image](https://user-images.githubusercontent.com/1326315/53370863-76657300-3914-11e9-8f97-39370e36518b.png)

**Comment by tboyce021** [comment]
Wrong button...

**Comment by pvizeli** [comment]
As I see that on tinker boards, a reboot solve the issue. Anyway: Boot 3 times and it go back to the old installation. Look like a systemd target is not loaded :/

**Comment by tboyce021** [comment]
I think it might be hosed. Rebooted several times and still same issue. I tried booting system 0 and 1 and neither seems to work. Anything else I can try? I'm not too concerned if I have to do a clean install though since I'm mostly just testing the setup right now.

**Comment by tboyce021** [comment]
Any way I can test the fix? I can't seem to mount the system rw to edit that file. I tried just building a new image but the build fails telling me it can't find hassos-hostapps locally and pull access is denied.

**Comment by tboyce021** [comment]
I ended up updating it by building an image with #370 and then using dd to replace my existing partition with the one with the fix. If I boot up with the original data partition, I can see the change on the filesystem. However, I still can't boot with an external data partition.

I got a better screenshot of the error messages:
![image](https://user-images.githubusercontent.com/1326315/53764782-d79cc180-3e93-11e9-9810-0531694b96ce.png)

Not sure if they're just printed out of order, but it looks like the data partition is getting mounted after it already fails?

**Comment by pvizeli** [comment]
Yes, it looks like you have right. The question and what we do not see, why this fails? It should wait until the device is available...

**Comment by tboyce021** [comment]
Not sure what was going on. I did a clean install with #370 and went through the process of moving the data partition to a separate disk again. Currently seems to be working again :man_shrugging:.

**Comment by tboyce021** [comment]
Tried again without resizing and still same issue. Works for the first boot but subsequent boots all get stuck. There is no [FAILED] in the logs, but the dependencies still fail and don't seem to be waiting.

![image](https://user-images.githubusercontent.com/1326315/53892602-38daa700-3ff2-11e9-9d55-748580af9e6d.png)

**Comment by tboyce021** [comment]
I managed to fix this based on a comment in [#164](https://github.com/home-assistant/hassos/issues/164#issuecomment-472788621).

When running `dd` to copy the partition, if I specify `of=/dev/sdb1` it will only work for the first boot. Specifying `of=/dev/sdb` works for reboots as well. I assume it has something to do with being the whole disk rather than a partition on the disk, but I'm not sure exactly why it doesn't work for a partition.

**Comment by pvizeli** [comment]
You need remove the old partition

**Comment by s00500** [comment]
Hi everyone, I just experienced something similar: I am running the hassio image on a RPi4 and I got the "Started Update UTMP... " error.
After checking the boot process again I noticed that the hassos-data partioion was not mounted due to block damage, inserting my SD into a linux box proved the same. I ran filesystem repair using gparted and could repair the disk, now everything works again :-)

Just wanted to put this here in case anyone lands here as I did, no need to reopen this or anything ;-)

**Comment by cigas4** [comment]
> 
> 
> Hi everyone, I just experienced something similar: I am running the hassio image on a RPi4 and I got the "Started Update UTMP... " error.
> After checking the boot process again I noticed that the hassos-data partioion was not mounted due to block damage, inserting my SD into a linux box proved the same. I ran filesystem repair using gparted and could repair the disk, now everything works again :-)
> 
> Just wanted to put this here in case anyone lands here as I did, no need to reopen this or anything ;-)

Hi,

Seems that I have same problem, Data and/or Overlay partition cant be mounted during startup. Could you please explain me how you performed file system repair? I have tried gparted software and also terminal with fsck function, but I always get same message that partition is read-only and not possible to check/repair. I would appreciate detailed instructions (as I am newbie on linux) for file system repair. Thank you in advance!

**Comment by estiens** [comment]
I have this same problem after updating HassOS and now can't boot...
