### ISSUE TITLE
Unmount errors during HASSOS (2.10) Shutdown

### ISSUE THREAD

**Issue by MwC-Trexx** [home-assistant/hassos#371]
During HASSOS shutdown, several unmount errors are being recorded>

**OS:** HASSOS 2.10
**Platform:** QEMU_x64
**HASSIO version:** 0.87.1

During HASSOS shutdown, the following errors are being being shown (see screenshots).

<img width="1136" alt="screen shot 2019-02-26 at 2 40 26 pm" src="https://user-images.githubusercontent.com/7128246/53445018-3adead80-39d5-11e9-8b8a-3ef4844c89b9.png">

I wonder if this is what is causing some corruption of HASSOS VM's if there are frequent shutdown/reboots.

**Comment by jvanderneutstulen** [comment]
Maybe unmounting fails because of corruption. Can you capture a more complete log using a serial console?

**Comment by MwC-Trexx** [comment]
I will see what I can do.... since QNAP Virtualization Station is based around QEMU/KVM, it MIGHT be possible to do something at CLI level, but not sure. There definitely isn't a console "log" option as far as I am aware.

Based on the screen logs/error messages is seemed more like a code issue 

- Docker container unmoun: Invalid Argument.
- Overlay2 unmount: Invalid Argument

I am still a semi-novice in some of this space though.

**Comment by jvanderneutstulen** [comment]
It is also possible to use a GUI, for example virt-manager. You can select the 'text console' you want to use. Just append `console=ttyS0,115200n8` to the `cmdline.txt`.

**Comment by MwC-Trexx** [comment]
No such luck.  Qnap doesn't leverage virt-manager nor expose libvirtd externally.

**Comment by pvizeli** [comment]
Should fix with 2.11?
