### ISSUE TITLE
Support for Wireless Zigbee CC2531 USB stick / Zigbee2MQTT

### ISSUE THREAD

**Issue by 2xdehelft** [home-assistant/hassos#375]
When using HASSOS on VMWare ESXi 6.7 the CC2531 USB stick is not recognized by Hassio. 
![image](https://user-images.githubusercontent.com/33652012/54269598-ed8a4080-457d-11e9-8549-05d64cb6fc19.png)

Ive redirected the stick to the VM in ESXi. 

![image](https://user-images.githubusercontent.com/33652012/54269146-152cd900-457d-11e9-95b3-92925a5183a9.png)

But nothing in the Hassio hardware list:

![image](https://user-images.githubusercontent.com/33652012/54269526-cdf31800-457d-11e9-8f54-d43bf15e1edd.png)

![image](https://user-images.githubusercontent.com/33652012/54295379-2f81a980-45b3-11e9-8128-c7a586056924.png)
dmesg | grep -i usb output....

**Comment by 2xdehelft** [comment]
![image](https://user-images.githubusercontent.com/33652012/54291232-90f24a00-45ac-11e9-8a87-191a66e3f0a4.png)
dmesg | grep -i usb output....

**Comment by joopy** [comment]
some problem no solution?
