### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by ifly3years** [home-assistant/hassos#383]
when i update my hassos , 
use the "update" link in system ---->host system
>>>>http://192.168.15.XX:8123/hassio/system

 i got  this info ;
____________________________________________________
Error: 500 Internal Server Error Server got itself in trouble
____________________________________________________
and system log said:
19-03-22 10:57:52 INFO (MainThread) [hassio.hassos] Fetch OTA update from https://github.com/home-assistant/hassos/releases/download/2.10/hassos_ova-2.10.raucb

____________________________________________________

i think，something was wrong, because ,i have 3.0 hassos, not the 2.10;
so, how can i find the code and repair it? 
thanks

**Comment by ifly3years** [comment]
oh，no!!!

i click the update button,,,,,and this time it's ok, 
he did it , an downgrade my system to 2.10......

oh, ,,,,,,

**Comment by pvizeli** [comment]
Yes, this button is only for stable development circle.
