### ISSUE TITLE
VMDK: Docker top error

### ISSUE THREAD

**Issue by tboyce021** [home-assistant/hassos#388]
Running `docker top homeassistant` on the host gives the following error:

```
ps: ps: invalid option -- 'e'
```

Using the VMDK with Proxmox on a NUC:
```
 System: HassOS 2.11  (amd64 / qemux86-64)
 Home Assistant version: 0.90.2
 Supervisor version: 152
```

This seems to be preventing the Portainer add-on from displaying container stats (see [hassio-addons/addon-portainer#3](https://github.com/hassio-addons/addon-portainer/issues/3#issuecomment-478739830)).

**Comment by pvizeli** [comment]
You can use our API: /homeassistant/stats

**Comment by tboyce021** [comment]
I'm not sure the API is sufficient for this. The Portainer addon allows for installing containers that are **not** addons, but the API won't return the stats for those. Also, I'm not sure if there's a way to customize Portainer to use that API instead of docker top/ps.
