### ISSUE TITLE
FeatureRequest: Upgrade NetworkManager for Wireguard Support

### ISSUE THREAD

**Issue by gregod** [home-assistant/hassos#394]
Hi,
since the 1.16.0 release NetworkManager supports wireguard vpn profiles natively as connection profiles which would be great to have in hassos.

I haven't fully understood the buildroot configuration management process. Upstream buildroot it is still  at 1.14, this local fork is at 1.10. 
Could we patch this locally? *(Should we ? Connectivtiy is maybe not the place to experiment.)*

**Comment by pvizeli** [comment]
Look into buildroot-patches folder. There are other packages they I had manually updated.
