### ISSUE TITLE
How to set kernel param vm.max_map_count=262144

### ISSUE THREAD

**Issue by jonn26** [home-assistant/hassos#399]
I am trying to run an elasticsearch container that requires the following to be set in /etc/sysctl.conf

vm.max_map_count=262144

I can set it temporarily with:

sysctl -w vm.max_map_count=262144

How can I set this in hassos so it is persistent?

**Comment by pvizeli** [comment]
There are no mechanics for persistent. Feel free to provide a feature for that with systemd. I will merge such feature.
