### ISSUE TITLE
Add new packackages "INK" & "HPLIP"

### ISSUE THREAD

**Issue by pergolafabio** [home-assistant/hassos#410]
Hi, to read out toner/ink level for printers, for creating toner sensors
some extra packages needs to be installed
HPLIP & INK

is it possible to add this in future release?

thnx in advance

**Comment by bouwew** [comment]
This refers to this discussion: https://community.home-assistant.io/t/custom-component-for-printer-ink-levels/36431/45

As written there, no use to include them in the Hassio docker.
