### ISSUE TITLE
Odriod C2 2.12 or 3.1 img cannot get network link up

### ISSUE THREAD

**Issue by namiba** [home-assistant/hassos#411]
I downloaded the latest 2.12 as well as 3.1 of Hassos for the C2. Flashed SD card with etcher and viewed the boot messages via console, but there is no network link on C2 or switch with the default DHCP config. I also tried with a static IPv4 but still no network link.

On the console debug shows a lot of IPv6 and link not ready and finally shows link ready but the link light on the C2 or switch does not light. I cannot ping out after using nmcli and setting the C2 to static IP. 

Has anyone tried with these versions on the Odriod C2?

**Comment by rbray89** [comment]
hmmm... I'm running on 2.11 without any problems. Can you try that version quickly to eliminate config or HW issues?

**Comment by rbray89** [comment]
Hmmm... Just performed an OTA update to 2.12, and everything looks good here. Did you create a network config for it? Syntax errors can cause this problem. Try deleting any network configs already present and reboot to restore defaults if you haven't already.
