### ISSUE TITLE
Raspberry Pi 4-image

### ISSUE THREAD

**Issue by pepeEL** [home-assistant/hassos#413]
Hi
Now is released Raspberry Pi 4 :) 
When we can think that image for Raspberry Pi 4 will be available ?

**Comment by homeassistantmi2** [comment]
Can yo release immediately hassos on Rpi4 ? 
Only option now is use manual installation on linux
ResinOS it also not work on rpi4

**Comment by Joeboyc2** [comment]
Just wait a little bit, give the devs a chance!

**Comment by pepeEL** [comment]
And good will be add support boot from ssd on usb3. 0
This is very need.

**Comment by pvizeli** [comment]
We can first add support for RPi4 if u-boot (our bootloader they we use because we are a embedded system) have a support patch.

**Comment by skynet01** [comment]
Would be amazing if we can just take out our sd  card from Rpi3 and stick it in Rpi4 and it just starts working like nothing happend 🥰

**Comment by Joeboyc2** [comment]
I think that's an impossibility due to the changes thr new hardware has.

Nothing wrong with starting again 😁

**Comment by pvizeli** [comment]
@Joeboyc2 have right, there are complete different bootloader and microcode to setup the CPU and start the kernel. Raspbian work a bit different, they can handle that because they but everthing into same image and support only 32bit.

**Comment by pvizeli** [comment]
Support start with 3.3

**Comment by skynet01** [comment]
Woohoo! Thank you!

**Comment by Joeboyc2** [comment]
I'll be flashing it tonight, will let you know of I have any issues 😁

**Comment by Joeboyc2** [comment]
oh.... @pvizeli i dont see the pi 4 image.... which one should i use to flash ? the pi3 one?

**Comment by MrYadro** [comment]
You just have to wait a bit while they are building, now they are up in assets

**Comment by skynet01** [comment]
So stoked to try it. Is there going to be a migration tutorial of some sort from Pi3+? Or you just flash it and restore a snapshot?

**Comment by Joeboyc2** [comment]
Ah i see them now, literally only 22 assets when i check and sent the message, 24 now :)
