### ISSUE TITLE
auth-alg with WPA

### ISSUE THREAD

**Issue by rmariboe** [home-assistant/hassos#433]
The readme says to use auth-alg=open with WPA rather than auth-alg=shared.
“Open” is the WPE standard, whereas “shared” (pre shared key) is for WPA. 

https://developer.gnome.org/NetworkManager/stable/nm-settings.html

**Comment by pvizeli** [comment]
Work with my WPA setup. Anyway make a PR please if we do it wrong. Thanks

**Comment by rmariboe** [comment]
Odd, it contradicts the Gnome NM man - I’ll test it when I get was faulty because of other people reporting difficulties 🤷🏽‍♂️:)
