### ISSUE TITLE
HassOS 2.11: EXT4-FS error 

### ISSUE THREAD

**Issue by friendodevil** [home-assistant/hassos#441]
Recently (with 0.95.3, 4 and now with 0.96.x) started getting file system errors in HassOs: 
EXT4-FS error ext4_mb_generate_buddy:747.

Running HassOS 2.11 in Oracle VM Virtual box. Not sure how to get started with fixing these. Help appreciated.

![Virtual box HassOs error](https://user-images.githubusercontent.com/40683291/61662763-bc620f80-acd7-11e9-831e-cebd4c0e3a45.png)

**Comment by pvizeli** [comment]
extfat4 should be self-healing with journal. Do you see other issues?

**Comment by friendodevil** [comment]
Have noticed that sometimes HassOS gets stuck and requires a VM machine
restart,  not sure its related.

**Comment by roybosch** [comment]
This seems to be closed, but I (and many others, so it seems) have this same problem:

https://community.home-assistant.io/t/ext4-fs-error-validating-inode-bitmap/163287/4

https://community.home-assistant.io/t/ext4-mb-generate-buddy-747/104860/6

Nothing is being self-healed, HA seems to get more and more corrupt until it doesn't boot at all.

**Comment by blamaz** [comment]
I'm running vbox vm and also having the same problem to a point that HassOS just hang on reboot.  I have to do a vm api shutdown to resolve it. Cannot use reboot fonction for now.

**Comment by roybosch** [comment]
> I'm running vbox vm and also having the same problem to a point that HassOS just hang on reboot. I have to do a vm api shutdown to resolve it. Cannot use reboot fonction for now. This issue is closed but problem remain.

What do you mean with a VM api shutdown? Is that a way to solve a corrupt VM?

**Comment by blamaz** [comment]
> What do you mean with a VM api shutdown? Is that a way to solve a corrupt VM?

Sorry, I meant ACPI shutdown from the Virtualbox UI

**Comment by iotinkognito** [comment]
Also still getting these issues.
