### ISSUE TITLE
hyper-v hassio won't start - no space left because log file take all space

### ISSUE THREAD

**Issue by lpt2007** [home-assistant/hassos#445]
Hi,

Is there a way to delete home-assistant.log file if I can't boot to hassos because no space left?

Log file eat all the space.

Only SHELL is working on boot menu.

**Comment by pvizeli** [comment]
resize the hard disk and the boot script should resize it later on boot

**Comment by lpt2007** [comment]
Hi,

I try to resize but not working.

My soultion to get data is to use free [linux reader](https://www.diskinternals.com/linux-reader/) on win10.

Then I used fresh image form [releases](https://github.com/home-assistant/hassos/releases) and data restore.
