### ISSUE TITLE
On Raspberry pi 4: /sys/class/thermal/thermal_zone0/temp

### ISSUE THREAD

**Issue by yashijoe** [home-assistant/hassos#447]
[Errno 22] Invalid argument

Thank you!
Kind regards

**Comment by andyfowler** [comment]
@yashijoe What command were you trying to run? I can see the temperature of my rPi 4 running the 3.3 dev build of hassos.

```
# uname -a
Linux hassio 4.19.58-v7l #1 SMP Tue Jul 16 20:31:47 UTC 2019 armv7l Hassio/OS
# cat /sys/class/thermal/thermal_zone0/temp
78880
```

(Yep, it's that hot…)

**Comment by yashijoe** [comment]
The situation is getting worse. Now also my DIN Bticino/Legrand relays and power consumption modules have the notification of update.
I'm getting the same "wrong image" message as for the micromodule switch and power socket.
