### ISSUE TITLE
Stacktrace during boot - Raspberry Pi 4

### ISSUE THREAD

**Issue by Joeboyc2** [home-assistant/hassos#448]
**Home Assistant release with the issue:**

Latest - 0.96.5
**Operating environment (HassOS/Generic):**

HassOS
**Supervisor logs:**

Unable to access

**Description of problem:**
I've recently migrated my install from a Raspi3 to a 4,.

I ran a fresh install on a new SD card and then restored a full snapshot, everything was working well and i went to move the pi to a new location, i shutdown using the shutdown option in the hassio console, and then started the pi up, it came back online but when i accessed the interface nothing loaded, i just had blue bar across the top.

I rebooted the pi a few more times (removing power and adding again), still no luck, i eventually plugged a hdmi cable in (i run the pi headless usually) and saw a stacktrace on the console, the device was not on the network and i have had to now re-flash the SD card and start again

![20190729_185623](https://user-images.githubusercontent.com/8202030/62086153-68b27180-b255-11e9-8a7c-b48380e81426.jpg)

![20190729_185318](https://user-images.githubusercontent.com/8202030/62086172-72d47000-b255-11e9-8933-d8d678c8f5dd.jpg)

**Comment by pvizeli** [comment]
Look like a memory issue or so. Maybe fix with a firmware update of RPi4

**Comment by Joeboyc2** [comment]
got it again, most annoying :(
![20190815_074849](https://user-images.githubusercontent.com/8202030/63113106-b9caa100-bf89-11e9-8db2-d314fec70f18.jpg)
