### ISSUE TITLE
Does not boot on Raspberry Pi 2 with the RaZberry daughter card

### ISSUE THREAD

**Issue by darkbasic** [home-assistant/hassos#452]
I've tried both 2.12 and 3.3, but none of them works on my Raspberry Pi 2 with the RaZberry daughter card.
It says "no ethernet found", then scans for usb devices and then immaediately drops me on a command prompt.
It boots if I remove the RaZberry daughter card.

**Comment by pvizeli** [comment]
Maybe a uboot issue

**Comment by rbray89** [comment]
I think you need to enable UART in the config.txt in the boot sector for this to work.
