### ISSUE TITLE
RPi 4 Wifi Connection Problems

### ISSUE THREAD

**Issue by fjfricke** [home-assistant/hassos#461]
I tried the new release 3.4 with the RPi 4 (32 Bit). The Raspberry connects to the wifi on the very first boot but not afterwards. If I disconnect the device from the power supply and connect it again, it cannot connect again.

**Comment by fjfricke** [comment]
It could also be the case that the device doesn't boot at all. Will check if it works with LAN tomorrow.

**Comment by pvizeli** [comment]
Check the content of `/mnt/overlay/etc/NetworkManager`

**Comment by fjfricke** [comment]
There is one file in system-connections/my-network which is the same as the one I created for the fist boot.
It's wiered: This time after I reformatted my sd card, it connected to the wifi twice but not after that.

**Comment by pvizeli** [comment]
what is the log of NetworkManager?

**Comment by fjfricke** [comment]
Where do I find the log file? I couldn't find it on my device..

**Comment by pvizeli** [comment]
`journalctl`

**Comment by fjfricke** [comment]
Apparently the problem was that I put an hassio backup into the backup folder on the SD card and it was not booting afterwards. I did it via Samba and now it is working.
