### ISSUE TITLE
There is a Home Assistant / Hass.io / HassOS. Which kind of the update do you means?

### ISSUE THREAD

**Issue by iannecj** [home-assistant/hassos#462]
There is a Home Assistant / Hass.io / HassOS. Which kind of the update do you means?

Edit: Don't post on PRs. You can open a issues and provide more details.

_Originally posted by @pvizeli in https://github.com/home-assistant/hassos/pull/459#issuecomment-526114394_

**Comment by iannecj** [comment]
Apologies for posting in wrong place, your note helped though...I had updated HA and not hassio (I am a newbie HA user and a newbie git user).

I can confirm 4GB now showing on my sysmon sensor for my RPI4B with 4GB.

**Comment by pvizeli** [comment]
Small tipps:
```
hassio ha update
hassio su update
hassio os update
```

This command can you use for update HomeAssistant/Hass.io (aka Supervisor)/HassOS
