### ISSUE TITLE
NOAA Tides

### ISSUE THREAD

**Issue by tanders587** [home-assistant/hassos#464]
While running home assistant in docker, if I have NOAA_tides integration enabled I get the following error.
https://paste.ubuntu.com/p/P3ZSFBzfG5/

**Comment by pvizeli** [comment]
Wrong repository. Register your component in our portal to build wheels for it.

**Comment by tanders587** [comment]
This is not my component it is found at https://www.home-assistant.io/components/noaa_tides/

**Comment by pvizeli** [comment]
Maybe you mean this. https://github.com/home-assistant/home-assistant/commit/4d08e73e3eb5db0391ca86488648b8acce95521d

Look like the maintainer of noaa did not want to run this on docker. I give it free now for you.

**Comment by pvizeli** [comment]
In around 4 hours it should work
