### ISSUE TITLE
Release 3.5 is missing RPI assets

### ISSUE THREAD

**Issue by libo** [home-assistant/hassos#478]
https://github.com/home-assistant/hassos/releases/tag/3.5 is missing:
```
- hassos_rpi-3.5.img.gz
- hassos_rpi-3.5.raucb
```

<img width="517" alt="Screenshot 2019-09-13 at 17 55 21" src="https://user-images.githubusercontent.com/37512/64876674-f30d3400-d64f-11e9-8fdf-7d18f39ce2a2.png">

**Comment by pvizeli** [comment]
https://dev.azure.com/home-assistant/Hass.io/_build/results?buildId=8784&view=results

**Comment by libo** [comment]
Ups... sorry mate :-)
