### ISSUE TITLE
Hassos on rpi 4 get only a blank screen at boot

### ISSUE THREAD

**Issue by jirmjos** [home-assistant/hassos#479]
Triying to install Hass.io with last stable Hassos image v3.4 (using path : https://github.com/home-assistant/hassos/releases/download/3.4/hassos_rpi4-3.4.img.gz) on brand new rpi 4, but not showing any image on screen.
I´m see that Hassos ver v3.5 seems not yet ready for pi4, so there are any workarround to solve the issue with the image for Hasso v3.4 ??

**Comment by pvizeli** [comment]
Fix with 3.5

**Comment by jirmjos** [comment]
Wooow !!!
This is as light !!!

Thank you so much.
