### ISSUE TITLE
Please add the possibility to move the recorder to external USB SSD.

### ISSUE THREAD

**Issue by sblantipodi** [home-assistant/hassos#494]
As title.
Recording a lot of sensors on microSD burns it fast.

Please add the possibility to move the recorder to external USB SSD.

**Comment by poudenes** [comment]
Maybe possible to use mysql and store the dB on a different storage?

**Comment by Joeboyc2** [comment]
Have you checked out the influxdb addon, that could probably help you out,
or take a look the documentation for the recorder component to tune it
outout

**Comment by sblantipodi** [comment]
> Maybe possible to use mysql and store the dB on a different storage?

this requires a NAS or something similar with really low latency access, 
USB disk is an easyer/cheaper solution.

**Comment by pvizeli** [comment]
You can setup a database on a database server and use that. Please no feature requests as PR.

**Comment by sblantipodi** [comment]
> You can setup a database on a database server and use that. Please no feature requests as PR.

@pvizeli it is not possible with hassio that is the only reason why hassos exist.
hassio can't use a VPN for this, no VPN, no way to setup a database server, I mean, I don't think that someone want to expose a DB over the internet.
