### ISSUE TITLE
RasberryPi 4 Firmware

### ISSUE THREAD

**Issue by Veldkornet** [home-assistant/hassos#498]
**Operating environment (HassOS/Generic):** RaspberryPi 4 64-bit 4 GB / HassOS

**Description of problem:**
The RaspberryPi 4 has had a [firmware update](https://www.tomshardware.com/features/raspberry-pi-4-firmware-cool-temps-network-boot) which improves the temperatures on the device, as well as some other fixes.
It wasn’t clear to me though if this is already included or not. If possible, could it please be included?

**Comment by pvizeli** [comment]
It's included. You can't run a RPi4 without cooling on high load like an smart home hub ;)
