### ISSUE TITLE
Not booting on RPI3B (32bit/64bit)

### ISSUE THREAD

**Issue by Sloth-on-meth** [home-assistant/hassos#499]
morning!

I've used 3 power supplies and 4 different SD cards, and redownloaded the image thrice. Sadly, on the pi3B (rev1.2), HassOS boots to the login screen, and then breaks, as in, it's inaccesible through the browser, and sometimes it even kernel panics. Someone else i was talking to on discord had the same issue. has anyone been able to setup HASSIO on the newest version on a PI3B?

**Comment by peyotll** [comment]
I don't have a screen but I can't access my PI3B after putting the SD card and waiting 20mn to 2h. It seems there is no network activity either even if i's plugged to the router and has Internet access.
