### ISSUE TITLE
Update ftom GUI - downloaded very old version.

### ISSUE THREAD

**Issue by pepeEL** [home-assistant/hassos#514]
Hi 
I have installed on my RPI3 image Hassos 3.5
Now i want update to version 3.6. In gui hassio>System> by click UPDATE he downloaded me very old version 2.12
No download me version 3.6. Why ? It is bug ? Please help....

**Comment by pvizeli** [comment]
Yes, 3.6 is only available on Beta channel. If you move back to stable channel or you run on stable channel, you get the latest stable release and that is 2.12
