### ISSUE TITLE
Bluetooth BCM43xx fail

### ISSUE THREAD

**Issue by jasimancas** [home-assistant/hassos#52]
I have installed the addon Bluetooth BCM43xx, but the devices dont report.

Raspberry PI3B

The log of the add-on:

> bcm43xx_init
Flash firmware /lib/firmware/brcm/BCM43430A1.hcd
Set BDADDR UART: b8:27:eb:60:46:d0
Set Controller UART speed to 921600 bit/s
Device setup complete

I have https://www.home-assistant.io/components/sensor.mitemp_bt/ and https://www.home-assistant.io/components/sensor.miflora/

**Comment by tyborall** [comment]
I think the Pi 3 B(+?) hast another BCM5xxx.

**Comment by jasimancas** [comment]
Is the 3B, not +, in hassio with ResinOS (old version) work fine, but in hassos (new version) not. Same files in Config folder and same add-ons install.

**Comment by pvizeli** [comment]
Do you use the same `config.txt`?

**Comment by jasimancas** [comment]
The same config folder (home assistant).

**Comment by pvizeli** [comment]
Can you look into `config.txt` on boot partition of hassos and resinos and look if you change there something?

If that the same, can you copy the start.elf, fix-up.bin and bootcode.bin to hassos? Maybe the is a bug RPI firmware.

**Comment by jasimancas** [comment]
Ok, look this:
Hassio:
![hassio](https://user-images.githubusercontent.com/15717847/42102786-5238c4c4-7bc7-11e8-8c61-ea69baeb8495.JPG)
Hassos:
![hassos](https://user-images.githubusercontent.com/15717847/42102789-5412ae4a-7bc7-11e8-82f7-cb2ddf8a5c87.JPG)

**Comment by pvizeli** [comment]
The mac address is strange

**Comment by jasimancas** [comment]
Yes, maybe this is the problem.

**Comment by danielsjf** [comment]
If it helps anything, I tried the same on my raspberry pi 3 model B+. The ip also ends in aa, but also the rest is exactly the same.

**Comment by pvizeli** [comment]
I move that to add-on repository and try to fix the add-on

**Comment by pvizeli** [comment]
I'm worng: https://www.raspberrypi.org/forums/viewtopic.php?t=183474

Is that only with 64bit or also with 32bit a problem?

**Comment by jasimancas** [comment]
Both, 32 and 64

**Comment by pvizeli** [comment]
I try to extract the correct serial number from device tree

**Comment by pvizeli** [comment]
Okay, I provide the bugfix they was describe there in HassOS 1.2

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassos/issues/62

Will be release today

**Comment by pvizeli** [comment]
I was right, the problem is on add-on. On new linux version they need read the device-tree for serialnumber and not /proc/cpu. I fix that now on add-on
