### ISSUE TITLE
raspberry pi hassos image - how I can extand partition tu use full sdcard space?

### ISSUE THREAD

**Issue by lpt2007** [home-assistant/hassos#527]
Raspberry pi hassos image - how I can extend partition to use full sdcard space?

**Comment by pvizeli** [comment]
It's done automatically

**Comment by pepeEL** [comment]
Hmmm i think that no automatically because if i good remember i remove card from RPI and insert it to PC and partition is not full resize....

**Comment by pvizeli** [comment]
I run a test with 3.7 and it work perfect. Also with OVA image. However, your PC need support hyprid partition, otherwise you see the wrong partition layout.

**Comment by lpt2007** [comment]
I try with fresh install of hassos_rpi2-3.7.img on 8Gb sdcard:

I can use only 6.6Gb:

<img width="384" alt="fresh_install_no_full_ssd" src="https://user-images.githubusercontent.com/38924279/71981700-3143ea00-3223-11ea-8493-4f783d29354d.png">
