### ISSUE TITLE
HassOS on RPI3B+ unable to boot off SSD while ok with raspian

### ISSUE THREAD

**Issue by marcgarciamarti** [home-assistant/hassos#535]
RPI3B+ won't boot off an attached SSD etched with hassos 3.7. After doing some troubleshooting if found out that the same setup but with raspian works as expected.

This is the SSD: APPLE SSD SM128C                        

And this is the enclosure: https://www.transcend-info.com/Products/No-624

and here some log activity framing why I believe there is an issue with hassos   https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=260225&p=1593598#p1593598

thanks

**Comment by pvizeli** [comment]
could be, we use u-boot for booting and the restriction factor is the limited hardware support on u-boot. See: https://github.com/home-assistant/hassos/blob/dev/Documentation/boards/raspberrypi.md#caveats

There is a list on community board with hardware they is tested by community.
