### ISSUE TITLE
Bluetooth not working well

### ISSUE THREAD

**Issue by paskyecijano** [home-assistant/hassos#63]
On the RPI3, I have this device https://www.home-assistant.io/components/sensor.mitemp_bt/ but can not read the info.

i think that the problem is this

bcm43xx_init
Flash firmware /lib/firmware/brcm/BCM43430A1.hcd
Set BDADDR UART: b8:27:eb:aa:aa:aa
Set Controller UART speed to 921600 bit/s
Device setup complete

the number MAC not is correct. b8:27:eb:**aa:aa:aa**

**Comment by pvizeli** [comment]
#52 

Is not a HassOS problem, the add-on problem
