### ISSUE TITLE
Missing official add-ons in add-on store

### ISSUE THREAD

**Issue by stenki-eu** [home-assistant/hassos#76]
Is there any repository link I could use?

**Comment by stenki-eu** [comment]
But no problems to add any other repositories...

**Comment by cogneato** [comment]
Did you just try a fresh install? When I've seen this problem elsewhere, a reflash has been the solution.

**Comment by stenki-eu** [comment]
yes, a new RPi 3b+ with the image "hassos_rpi3-64-1.2.img.gz"

**Comment by pvizeli** [comment]
Can you post supervisor logs of startup? How fast is you internet connection?
