### ISSUE TITLE
Rename the hostname in HASSOS?

### ISSUE THREAD

**Issue by stenki-eu** [home-assistant/hassos#77]
Is it possible to rename the hostname from HASSIO to HASSOS? It would avoid an unpleasantness with duplicate names in the network as long as people like me still use both systems at the same time.

**Comment by tyborall** [comment]
But Hassio is the supervisor. The name before was also not "resinos" for the host, so why should the name changed to "hassos"? But I would generally like the idea to have an option to change the hostname to a custom name...

**Comment by cogneato** [comment]
@tyborall @stenki-eu `hassio network options -o hostname=xy` is the command for the resinOS based hassio. You could do that instead, or try the same with HassOS and report back!

**Comment by stenki-eu** [comment]
`hassio ne options -o hostname=HASSOS` generates an error `Error decoding json invalid character ':' after top-level value: 404: Not Found#`

**Comment by pvizeli** [comment]
It is`host options` but not sure if someone add this to clients but supervisor support this. Jou can also use systems mechanical to change it.
