### ISSUE TITLE
Is Hass run as root? 

### ISSUE THREAD

**Issue by danielsjf** [home-assistant/hassos#87]
After reading [this](https://www.home-assistant.io/docs/configuration/securing/) article on the security of HA, I was wondering if Hass os runs it as root? Probably not, but just asking for clarity.

Also, are there any other security constraints we have to be aware of with Hass os? Any default passwords or things like that?

**Comment by pvizeli** [comment]
Home Assistant run inside a container protected on a AppArmor system without any default passwords:
- https://en.wikipedia.org/wiki/AppArmor
- https://en.wikipedia.org/wiki/Docker_(software)
