### ISSUE TITLE
Roadmap dev-2 / rel-3

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/hassos#89]
## Features OS
- Allow to use data partition on a USB drive

**Comment by ciotlosm** [comment]
Would be nice to have the ability to write the os on a usb device and have the ability for the rpi3 to boot from there

**Comment by rogersmj** [comment]
Any updates? I just want to hang a USB hard drive on the Pi and share it via Samba as a basic networked file share.

**Comment by Teri928** [comment]
I'm interested in this feature as well.

**Comment by esciara** [comment]
Can someone confirm that this feature is now available when following the steps described in https://github.com/home-assistant/hassos/issues/164#issuecomment-472788621, following the mentioned work done on #318 ?

**Comment by satreddys** [comment]
It's 2020 and this feature is not available yet. It would be better to use SD card only for boot drive and remaining partitions from external drive for OS longevity when compared with SD card life.

**Comment by austwhite** [comment]
Looks like this is closed as wont fix...... Guess it is not happening

**Comment by dhebard** [comment]
We really need this ability.

**Comment by austwhite** [comment]
We might need to open a new feature request for this one.
It was closed in April 2019 as there were no updates and no responses after the automatic system flagged it as stale.
Maybe someone can open a new request for this feature?

**Comment by dhebard** [comment]
Yes please!
